import { describe, test, expect, beforeEach, afterEach } from "bun:test";
import { mkdtempSync, mkdirSync, writeFileSync, existsSync, readFileSync } from "fs";
import { join } from "path";
import { tmpdir } from "os";
import {
  getSkillDocs,
  getSkillBestDoc,
  getSkillRequirements,
  generateEnvExample,
  generateSkillMd,
} from "./skillinfo";
import { installSkill } from "./installer";

let testDir: string;

beforeEach(() => {
  testDir = mkdtempSync(join(tmpdir(), "skillinfo-test-"));
});

afterEach(() => {
  const { rmSync } = require("fs");
  rmSync(testDir, { recursive: true, force: true });
});

describe("skillinfo", () => {
  describe("getSkillDocs", () => {
    test("returns docs for skill with SKILL.md", () => {
      const docs = getSkillDocs("image");
      expect(docs).not.toBeNull();
      expect(docs!.skillMd).toBeTruthy();
      expect(docs!.skillMd).toContain("Image Generation");
    });

    test("returns docs for skill with CLAUDE.md only", () => {
      const docs = getSkillDocs("deepresearch");
      expect(docs).not.toBeNull();
      expect(docs!.claudeMd).toBeTruthy();
    });

    test("returns null for nonexistent skill", () => {
      const docs = getSkillDocs("nonexistent-xyz");
      expect(docs).toBeNull();
    });

    test("returns null fields for missing doc files", () => {
      const docs = getSkillDocs("scaffold-project");
      expect(docs).not.toBeNull();
      // At least one doc exists
      const hasAny = docs!.skillMd || docs!.readme || docs!.claudeMd;
      // scaffold-project has CLAUDE.md at minimum
      expect(docs!.claudeMd).toBeTruthy();
    });
  });

  describe("getSkillBestDoc", () => {
    test("returns SKILL.md when available", () => {
      const doc = getSkillBestDoc("image");
      expect(doc).toBeTruthy();
      expect(doc).toContain("Image Generation");
    });

    test("falls back to CLAUDE.md", () => {
      const doc = getSkillBestDoc("deepresearch");
      expect(doc).toBeTruthy();
    });

    test("returns null for nonexistent skill", () => {
      const doc = getSkillBestDoc("nonexistent-xyz");
      expect(doc).toBeNull();
    });
  });

  describe("getSkillRequirements", () => {
    test("extracts env vars from image skill", () => {
      const reqs = getSkillRequirements("image");
      expect(reqs).not.toBeNull();
      expect(reqs!.envVars).toContain("OPENAI_API_KEY");
      expect(reqs!.envVars).toContain("GEMINI_API_KEY");
    });

    test("extracts CLI command from package.json", () => {
      const reqs = getSkillRequirements("image");
      expect(reqs).not.toBeNull();
      expect(reqs!.cliCommand).toBe("skill-image");
    });

    test("extracts CLI command for deep-research", () => {
      const reqs = getSkillRequirements("deepresearch");
      expect(reqs).not.toBeNull();
      expect(reqs!.cliCommand).toBe("skill-deepresearch");
    });

    test("returns null for nonexistent skill", () => {
      const reqs = getSkillRequirements("nonexistent-xyz");
      expect(reqs).toBeNull();
    });

    test("returns sorted env vars", () => {
      const reqs = getSkillRequirements("image");
      expect(reqs).not.toBeNull();
      const vars = reqs!.envVars;
      const sorted = [...vars].sort();
      expect(vars).toEqual(sorted);
    });

    test("extracts dependencies from package.json", () => {
      const reqs = getSkillRequirements("deepresearch");
      expect(reqs).not.toBeNull();
      expect(reqs!.dependencies).toHaveProperty("commander");
    });
  });

  describe("generateEnvExample", () => {
    test("returns empty string when no skills installed", () => {
      const result = generateEnvExample(testDir);
      expect(result).toBe("");
    });

    test("returns empty string when .skills dir does not exist", () => {
      const result = generateEnvExample(join(testDir, "nonexistent"));
      expect(result).toBe("");
    });

    test("generates env example from installed skills", () => {
      installSkill("image", { targetDir: testDir });
      const result = generateEnvExample(testDir);
      expect(result).toContain("OPENAI_API_KEY");
      expect(result).toContain("GEMINI_API_KEY");
      expect(result).toContain("# Used by: image");
    });

    test("includes header comments", () => {
      installSkill("image", { targetDir: testDir });
      const result = generateEnvExample(testDir);
      expect(result).toContain("# Environment variables for installed skills");
      expect(result).toContain("# Auto-generated by: skills init");
    });

    test("groups by provider prefix", () => {
      installSkill("image", { targetDir: testDir });
      const result = generateEnvExample(testDir);
      expect(result).toContain("# OPENAI");
      expect(result).toContain("# GEMINI");
    });
  });

  describe("generateSkillMd", () => {
    test("generates SKILL.md for a skill without one", () => {
      const md = generateSkillMd("deepresearch");
      expect(md).not.toBeNull();
      expect(md!).toContain("---");
      expect(md!).toContain("name: deepresearch");
      expect(md!).toContain("description:");
      expect(md!).toContain("Deep Research (Agentic)");
    });

    test("generates SKILL.md for a skill with existing SKILL.md source", () => {
      // image has a SKILL.md, but generateSkillMd still works
      const md = generateSkillMd("image");
      expect(md).not.toBeNull();
      expect(md!).toContain("name: image");
    });

    test("includes category and tags", () => {
      const md = generateSkillMd("deepresearch");
      expect(md).not.toBeNull();
      expect(md!).toContain("Category: Research & Writing");
      expect(md!).toContain("Tags:");
    });

    test("includes CLI section for skills with bin entry", () => {
      const md = generateSkillMd("deepresearch");
      expect(md).not.toBeNull();
      expect(md!).toContain("## CLI");
      expect(md!).toContain("skills run deepresearch");
    });

    test("returns null for nonexistent skill", () => {
      const md = generateSkillMd("nonexistent-xyz");
      expect(md).toBeNull();
    });

    test("has valid YAML frontmatter", () => {
      const md = generateSkillMd("deepresearch");
      expect(md).not.toBeNull();
      // Check frontmatter structure
      const parts = md!.split("---");
      expect(parts.length).toBeGreaterThanOrEqual(3);
      // Frontmatter is between first and second ---
      const frontmatter = parts[1];
      expect(frontmatter).toContain("name:");
      expect(frontmatter).toContain("description:");
    });
  });
});
