import {
  chmodSync,
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "fs";
import { createHash } from "crypto";
import { dirname, join, relative, sep } from "path";

import { getDataDir } from "./config.js";
import {
  AGENT_TARGETS,
  getAgentSkillsDir,
  getSkillPath,
  type AgentScope,
  type AgentTarget,
} from "./installer.js";
import { loadRegistry } from "./registry.js";
import type { SkillMeta, SkillSource } from "./registry-types.js";
import { getSkillRemovalLedgerEntry } from "./skill-removal-ledger.js";

export const SKILLS_RENDER_MANIFEST = ".skills-render-manifest.json";
export const SKILLS_RENDER_MANIFEST_VERSION = 1;
export const SKILLS_RENDER_MARKER = "<!-- Generated by skills render. Do not edit. -->";

export interface SkillRenderProvenance {
  source: SkillSource;
  sourcePath: string;
  version?: string;
}

export interface SkillRenderManifestEntry {
  sourceHash: string;
  renderedHash: string;
  provenance: SkillRenderProvenance;
}

export interface SkillRenderManifest {
  version: typeof SKILLS_RENDER_MANIFEST_VERSION;
  home: AgentTarget;
  skills: Record<string, SkillRenderManifestEntry>;
}

export interface SkillRenderHomeCheck {
  home: AgentTarget;
  path: string;
  missing: string[];
  drifted: string[];
  stray: string[];
  stale: string[];
  errors: string[];
}

export interface SkillRenderCheckResult {
  ok: boolean;
  homes: SkillRenderHomeCheck[];
}

export interface SkillRenderHomeResult extends SkillRenderHomeCheck {
  rendered: string[];
  archived: string[];
}

export interface SkillRenderResult {
  ok: boolean;
  homes: SkillRenderHomeResult[];
}

export interface SkillRenderOptions {
  agents?: AgentTarget[];
  scope?: AgentScope;
  projectDir?: string;
  archiveRoot?: string;
  archiveStrays?: boolean;
  /** Test/library override. CLI callers use the merged local registry. */
  registry?: SkillMeta[];
}

interface RenderedFile {
  path: string;
  bytes: Uint8Array;
  mode: number;
}

interface DesiredSkill {
  name: string;
  files: RenderedFile[];
  manifest: SkillRenderManifestEntry;
}

interface HomeState {
  home: AgentTarget;
  path: string;
  manifest: SkillRenderManifest | null;
  desired: Map<string, DesiredSkill>;
  check: SkillRenderHomeCheck;
  unownedEntries: string[];
  staleNames: string[];
}

/** Recompute every configured agent home without mutating it. */
export function checkRenderedSkillHomes(options: SkillRenderOptions = {}): SkillRenderCheckResult {
  const states = inspectHomes(options);
  const homes = states.map((state) => state.check);
  return { ok: homes.every(homeIsClean), homes };
}

/**
 * Materialize instruction skills into agent-native homes.
 *
 * All destructive-looking transitions are recoverable: old managed renders,
 * ledger-covered removals, and explicitly selected strays are moved into the
 * archive. A manifest entry that disappeared without a ledger record refuses the
 * entire operation before the first write.
 */
export function renderSkillHomes(options: SkillRenderOptions = {}): SkillRenderResult {
  const states = inspectHomes(options);
  const inspectionErrors = states.flatMap((state) => state.check.errors);
  if (inspectionErrors.length > 0) {
    throw new Error(`Refusing to render over invalid home state: ${inspectionErrors.join("; ")}`);
  }
  const unauthorized = states.flatMap((state) => state.staleNames
    .filter((name) => !getSkillRemovalLedgerEntry(name))
    .map((name) => `${state.home}:${name}`));
  if (unauthorized.length > 0) {
    throw new Error(
      `Refusing to remove rendered skills without a rename/removal ledger entry: ${unauthorized.join(", ")}`,
    );
  }

  const archiveRoot = options.archiveRoot ?? join(getDataDir(), "archive");
  const archiveStrays = options.archiveStrays ?? false;
  const homes: SkillRenderHomeResult[] = [];

  for (const state of states) {
    const rendered: string[] = [];
    const archived: string[] = [];
    mkdirSync(state.path, { recursive: true });

    for (const name of state.staleNames) {
      const target = join(state.path, name);
      if (existsSync(target)) {
        archivePath(target, archiveRoot, state.home, name);
        archived.push(name);
      }
    }

    if (archiveStrays) {
      for (const entry of state.unownedEntries) {
        const target = join(state.path, entry);
        if (!existsSync(target)) continue;
        archivePath(target, archiveRoot, state.home, entry);
        archived.push(entry);
      }
    }

    const stillUnowned = new Set(archiveStrays ? [] : state.unownedEntries);
    const nextEntries: Record<string, SkillRenderManifestEntry> = {};
    for (const [name, desired] of state.desired) {
      const target = join(state.path, name);
      // An unmanifested entry is user-owned even when its name collides with a
      // registry skill. Never overwrite it without --archive-strays.
      if (stillUnowned.has(name)) continue;

      const actualHash = hashDirectory(target);
      if (actualHash !== desired.manifest.renderedHash) {
        if (existsSync(target)) {
          archivePath(target, archiveRoot, state.home, name);
          archived.push(name);
        }
        writeRenderedDirectory(target, desired.files);
        rendered.push(name);
      }
      nextEntries[name] = desired.manifest;
    }

    const manifest: SkillRenderManifest = {
      version: SKILLS_RENDER_MANIFEST_VERSION,
      home: state.home,
      skills: sortRecord(nextEntries),
    };
    atomicWriteFile(join(state.path, SKILLS_RENDER_MANIFEST), `${JSON.stringify(manifest, null, 2)}\n`);

    const after = inspectHome(state.home, state.path, state.desired);
    homes.push({
      ...after.check,
      rendered: rendered.sort(),
      archived: archived.sort(),
    });
  }

  return { ok: homes.every(homeIsClean), homes };
}

function inspectHomes(options: SkillRenderOptions): HomeState[] {
  const agents = options.agents ?? AGENT_TARGETS;
  const desired = buildDesiredSkills(options.registry ?? loadRegistry());
  const scope = options.scope ?? "global";
  return agents.map((home) => {
    const path = getAgentSkillsDir(home, scope, options.projectDir);
    return inspectHome(home, path, desired);
  });
}

function inspectHome(home: AgentTarget, path: string, desired: Map<string, DesiredSkill>): HomeState {
  const errors: string[] = [];
  let manifest: SkillRenderManifest | null = null;
  try {
    manifest = readManifest(path, home);
  } catch (err) {
    errors.push((err as Error).message);
  }

  const owned = new Set(Object.keys(manifest?.skills ?? {}));
  const entries = listHomeEntries(path);
  const unownedEntries = entries.filter((entry) => entry !== SKILLS_RENDER_MANIFEST && !owned.has(entry));
  const staleNames = [...owned].filter((name) => !desired.has(name)).sort();
  const missing: string[] = [];
  const drifted: string[] = [];
  const stale = new Set(staleNames);

  for (const [name, skill] of desired) {
    const target = join(path, name);
    const recorded = manifest?.skills[name];
    if (!recorded || !existsSync(target)) {
      missing.push(name);
      continue;
    }
    if (!sameManifestEntry(recorded, skill.manifest)) stale.add(name);
    if (hashDirectory(target) !== skill.manifest.renderedHash) drifted.push(name);
  }

  return {
    home,
    path,
    manifest,
    desired,
    unownedEntries,
    staleNames,
    check: {
      home,
      path,
      missing: missing.sort(),
      drifted: drifted.sort(),
      stray: unownedEntries.sort(),
      stale: [...stale].sort(),
      errors,
    },
  };
}

function buildDesiredSkills(registry: SkillMeta[]): Map<string, DesiredSkill> {
  const desired = new Map<string, DesiredSkill>();
  for (const skill of registry.filter((entry) => entry.kind === "instruction").sort((a, b) => a.name.localeCompare(b.name))) {
    if (!isSafeEntryName(skill.name)) throw new Error(`Invalid registry skill name '${skill.name}'`);
    const sourcePath = resolveSkillSourcePath(skill);
    const sourceSkillMd = join(sourcePath, "SKILL.md");
    if (!isRegularFile(sourceSkillMd)) {
      throw new Error(`Instruction skill '${skill.name}' has no readable SKILL.md at ${sourceSkillMd}`);
    }

    const sourceFiles: RenderedFile[] = [readRenderedFile(sourceSkillMd, "SKILL.md")];
    for (const aux of ["references", "scripts"]) {
      const auxPath = join(sourcePath, aux);
      if (existsSync(auxPath)) collectAuxiliaryFiles(auxPath, aux, sourceFiles);
    }
    sourceFiles.sort((a, b) => a.path.localeCompare(b.path));

    const files = sourceFiles.map((file) => file.path === "SKILL.md"
      ? { ...file, bytes: new TextEncoder().encode(addGeneratedMarker(new TextDecoder().decode(file.bytes))) }
      : file);
    desired.set(skill.name, {
      name: skill.name,
      files,
      manifest: {
        sourceHash: hashFiles(sourceFiles),
        renderedHash: hashFiles(files),
        provenance: {
          source: skill.source ?? "official",
          sourcePath,
          ...(skill.version ? { version: skill.version } : {}),
        },
      },
    });
  }
  return desired;
}

function resolveSkillSourcePath(skill: SkillMeta): string {
  return getSkillPath(skill.name);
}

function collectAuxiliaryFiles(root: string, relativeRoot: string, files: RenderedFile[]): void {
  const stat = lstatSync(root);
  if (!stat.isDirectory()) throw new Error(`Auxiliary path must be a directory: ${root}`);
  for (const entry of readdirSync(root, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const absolute = join(root, entry.name);
    const childRelative = `${relativeRoot}/${entry.name}`;
    if (entry.isSymbolicLink()) throw new Error(`Refusing symbolic link in rendered auxiliary files: ${absolute}`);
    if (entry.isDirectory()) collectAuxiliaryFiles(absolute, childRelative, files);
    else if (entry.isFile()) files.push(readRenderedFile(absolute, childRelative));
    else throw new Error(`Unsupported auxiliary entry: ${absolute}`);
  }
}

function readRenderedFile(path: string, renderedPath: string): RenderedFile {
  const stat = lstatSync(path);
  return {
    path: renderedPath.split(sep).join("/"),
    bytes: readFileSync(path),
    mode: stat.mode & 0o777,
  };
}

function addGeneratedMarker(content: string): string {
  if (content.includes(SKILLS_RENDER_MARKER)) return content;
  const newline = content.includes("\r\n") ? "\r\n" : "\n";
  const frontmatter = content.match(/^---\r?\n[\s\S]*?\r?\n---(?:\r?\n|$)/);
  if (!frontmatter) return `${SKILLS_RENDER_MARKER}${newline}${content}`;
  return `${frontmatter[0]}${SKILLS_RENDER_MARKER}${newline}${content.slice(frontmatter[0].length)}`;
}

function readManifest(homePath: string, home: AgentTarget): SkillRenderManifest | null {
  const path = join(homePath, SKILLS_RENDER_MANIFEST);
  if (!existsSync(path)) return null;
  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(path, "utf8"));
  } catch {
    throw new Error(`Invalid render manifest: ${path}`);
  }
  if (!isObject(parsed)
    || parsed.version !== SKILLS_RENDER_MANIFEST_VERSION
    || parsed.home !== home
    || !isObject(parsed.skills)) {
    throw new Error(`Invalid render manifest: ${path}`);
  }
  for (const [name, entry] of Object.entries(parsed.skills)) {
    if (!isSafeEntryName(name) || !isManifestEntry(entry)) {
      throw new Error(`Invalid render manifest entry '${name}' in ${path}`);
    }
  }
  return parsed as unknown as SkillRenderManifest;
}

function isManifestEntry(value: unknown): value is SkillRenderManifestEntry {
  return isObject(value)
    && typeof value.sourceHash === "string"
    && typeof value.renderedHash === "string"
    && isObject(value.provenance)
    && typeof value.provenance.source === "string"
    && typeof value.provenance.sourcePath === "string";
}

function sameManifestEntry(a: SkillRenderManifestEntry, b: SkillRenderManifestEntry): boolean {
  return JSON.stringify(a) === JSON.stringify(b);
}

function listHomeEntries(path: string): string[] {
  try {
    if (!lstatSync(path).isDirectory()) return [];
    return readdirSync(path).sort();
  } catch {
    return [];
  }
}

function writeRenderedDirectory(target: string, files: RenderedFile[]): void {
  const staging = `${target}.rendering-${process.pid}-${Math.random().toString(16).slice(2)}`;
  try {
    mkdirSync(staging, { recursive: true });
    for (const file of files) {
      const path = join(staging, ...file.path.split("/"));
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, file.bytes, { mode: file.mode });
      chmodSync(path, file.mode);
    }
    renameSync(staging, target);
  } catch (err) {
    try { rmSync(staging, { recursive: true, force: true }); } catch {}
    throw err;
  }
}

function atomicWriteFile(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  const temporary = `${path}.tmp-${process.pid}-${Math.random().toString(16).slice(2)}`;
  try {
    writeFileSync(temporary, content, { flag: "wx" });
    renameSync(temporary, path);
  } catch (err) {
    try { rmSync(temporary, { force: true }); } catch {}
    throw err;
  }
}

function archivePath(source: string, archiveRoot: string, home: AgentTarget, entry: string): string {
  const date = new Date().toISOString().slice(0, 10);
  const base = join(archiveRoot, home, date);
  mkdirSync(base, { recursive: true });
  let destination = join(base, entry);
  for (let suffix = 1; existsSync(destination); suffix++) destination = join(base, `${entry}.${suffix}`);
  mkdirSync(dirname(destination), { recursive: true });
  renameSync(source, destination);
  return destination;
}

function hashDirectory(path: string): string | null {
  try {
    if (!lstatSync(path).isDirectory()) return null;
    const files: RenderedFile[] = [];
    collectDirectoryFiles(path, path, files);
    return hashFiles(files);
  } catch {
    return null;
  }
}

function collectDirectoryFiles(root: string, current: string, files: RenderedFile[]): void {
  for (const entry of readdirSync(current, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const absolute = join(current, entry.name);
    if (entry.isSymbolicLink()) throw new Error(`Symbolic link in rendered directory: ${absolute}`);
    if (entry.isDirectory()) collectDirectoryFiles(root, absolute, files);
    else if (entry.isFile()) files.push(readRenderedFile(absolute, relative(root, absolute)));
    else throw new Error(`Unsupported entry in rendered directory: ${absolute}`);
  }
}

function hashFiles(files: RenderedFile[]): string {
  const hash = createHash("sha256");
  for (const file of [...files].sort((a, b) => a.path.localeCompare(b.path))) {
    const path = Buffer.from(file.path, "utf8");
    hash.update(String(path.byteLength));
    hash.update(":");
    hash.update(path);
    hash.update(":");
    hash.update(String(file.bytes.byteLength));
    hash.update(":");
    hash.update(file.bytes);
    hash.update(":");
    hash.update(file.mode.toString(8));
    hash.update(";");
  }
  return hash.digest("hex");
}

function homeIsClean(home: SkillRenderHomeCheck): boolean {
  return home.missing.length === 0
    && home.drifted.length === 0
    && home.stray.length === 0
    && home.stale.length === 0
    && home.errors.length === 0;
}

function isSafeEntryName(name: string): boolean {
  return /^[a-z0-9][a-z0-9._-]*$/.test(name) && name !== "." && name !== "..";
}

function isRegularFile(path: string): boolean {
  try { return lstatSync(path).isFile(); } catch { return false; }
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function sortRecord<T>(record: Record<string, T>): Record<string, T> {
  return Object.fromEntries(Object.entries(record).sort(([a], [b]) => a.localeCompare(b)));
}
