import type { SkillMeta } from "../registry-types.js";

export const BUSINESS_MARKETING_SKILLS: SkillMeta[] = [
  {
    name: "ad-creative-generator",
    displayName: "Ad Creative Generator",
    description: "Generate ad creatives with copy, visuals, and layouts for marketing campaigns",
    category: "Business & Marketing",
    tags: ["ads", "creative", "marketing", "design"],
  },
  {
    name: "banner-ad-suite",
    displayName: "Banner Ad Suite",
    description: "Create banner ad sets in multiple sizes for display advertising campaigns",
    category: "Business & Marketing",
    tags: ["banner", "ads", "display", "marketing"],
  },
  {
    name: "campaign-metric-brief",
    displayName: "Campaign Metric Brief",
    description: "Generate campaign performance metric briefs and analytics summaries",
    category: "Business & Marketing",
    tags: ["campaign", "metrics", "analytics", "reporting"],
  },
  {
    name: "campaign-moodboard",
    displayName: "Campaign Moodboard",
    description: "Create visual moodboards for marketing and creative campaigns",
    category: "Business & Marketing",
    tags: ["campaign", "moodboard", "creative", "visual"],
  },
  {
    name: "caption-style-stylist",
    displayName: "Caption Style Stylist",
    description: "Style and format captions for social media and video content",
    category: "Business & Marketing",
    tags: ["captions", "social-media", "styling", "content"],
  },
  {
    name: "churn-risk-notifier",
    displayName: "Churn Risk Notifier",
    description: "Identify and notify about customer churn risk indicators",
    category: "Business & Marketing",
    tags: ["churn", "risk", "customer", "retention"],
  },
  {
    name: "competitor-ad-analyzer",
    displayName: "Competitor Ad Analyzer",
    description: "Analyze competitor advertising strategies, creatives, and messaging",
    category: "Business & Marketing",
    tags: ["competitor", "ads", "analysis", "marketing"],
  },
  {
    name: "crm-note-enhancer",
    displayName: "CRM Note Enhancer",
    description: "Enhance CRM notes with structured summaries and action items",
    category: "Business & Marketing",
    tags: ["crm", "notes", "sales", "enhancement"],
  },
  {
    name: "customer-journey-mapper",
    displayName: "Customer Journey Mapper",
    description: "Map and visualize customer journey touchpoints and experiences",
    category: "Business & Marketing",
    tags: ["customer-journey", "mapping", "ux", "marketing"],
  },
  {
    name: "email-campaign",
    displayName: "Email Campaign",
    description: "Design email marketing campaigns and newsletters with templates, sequences, and audience segmentation",
    category: "Business & Marketing",
    tags: ["email", "campaign", "marketing", "automation"],
  },
  {
    name: "feedback-survey-designer",
    displayName: "Feedback Survey Designer",
    description: "Design feedback surveys with optimized questions and response formats",
    category: "Business & Marketing",
    tags: ["survey", "feedback", "design", "questionnaire"],
  },
  {
    name: "customer-feedback-report",
    displayName: "Customer Feedback Report",
    description: "Generate premium customer feedback reports with clusters, sentiment, root causes, roadmap recommendations, evidence, and PDF/Markdown artifacts",
    category: "Business & Marketing",
    tags: ["feedback", "customer", "sentiment", "roadmap", "report", "premium", "remote"],
  },
  {
    name: "generate-social-posts",
    displayName: "Generate Social Posts",
    description: "Generate social media posts optimized for different platforms",
    category: "Business & Marketing",
    tags: ["social-media", "posts", "marketing", "content"],
  },
  {
    name: "landing-page-copy",
    displayName: "Landing Page Copy",
    description: "Write conversion-optimized landing page copy with headlines and CTAs",
    category: "Business & Marketing",
    tags: ["landing-page", "copywriting", "conversion", "marketing"],
  },
  {
    name: "onboarding-sequence-builder",
    displayName: "Onboarding Sequence Builder",
    description: "Build employee or customer onboarding sequences with steps and milestones",
    category: "Business & Marketing",
    tags: ["onboarding", "sequence", "workflow", "automation"],
  },
  {
    name: "outreach-cadence-designer",
    displayName: "Outreach Cadence Designer",
    description: "Design multi-touch outreach cadences for sales and marketing campaigns",
    category: "Business & Marketing",
    tags: ["outreach", "cadence", "sales", "marketing"],
  },
  {
    name: "partner-kit-assembler",
    displayName: "Partner Kit Assembler",
    description: "Assemble partner kits with brand assets, guidelines, and marketing materials",
    category: "Business & Marketing",
    tags: ["partner", "kit", "branding", "marketing"],
  },
  {
    name: "persona-based-adwriter",
    displayName: "Persona-Based Ad Writer",
    description: "Write targeted ads based on customer persona profiles",
    category: "Business & Marketing",
    tags: ["persona", "ads", "targeting", "copywriting"],
  },
  {
    name: "persona-generator",
    displayName: "Persona Generator",
    description: "Generate detailed customer and user personas for marketing and UX",
    category: "Business & Marketing",
    tags: ["persona", "generation", "marketing", "ux"],
  },
  {
    name: "product-demo-script",
    displayName: "Product Demo Script",
    description: "Write product demo scripts with talking points and flow",
    category: "Business & Marketing",
    tags: ["demo", "script", "product", "presentation"],
  },
  {
    name: "pitch-deck",
    displayName: "Pitch Deck",
    description: "Generate premium investor and sales deck packages with slides, speaker notes, design direction, PDF, and PPTX artifacts",
    category: "Business & Marketing",
    tags: ["deck", "presentation", "investor", "sales", "pptx", "premium", "remote"],
  },
  {
    name: "proposal-pack",
    displayName: "Proposal Pack",
    description: "Generate premium client proposal packages with proposal, statement of work, pricing, timeline, assumptions, cover email, and PDF/Markdown artifacts",
    category: "Business & Marketing",
    tags: ["proposal", "sow", "sales", "pricing", "timeline", "premium", "remote"],
  },
  {
    name: "sales-call-recapper",
    displayName: "Sales Call Recapper",
    description: "Recap sales calls with key points, objections, and follow-up actions",
    category: "Business & Marketing",
    tags: ["sales", "calls", "recap", "follow-up"],
  },
  {
    name: "salescopy",
    displayName: "Sales Copy",
    description: "Generate persuasive sales copy using AI for products and services",
    category: "Business & Marketing",
    tags: ["sales", "copywriting", "marketing", "persuasion"],
  },
  {
    name: "seo-brief-builder",
    displayName: "SEO Brief Builder",
    description: "Build SEO content briefs with keyword research and competitive analysis",
    category: "Business & Marketing",
    tags: ["seo", "brief", "content", "keywords"],
  },
  {
    name: "seo-content-pack",
    displayName: "SEO Content Pack",
    description: "Generate premium SEO content packages with topic clusters, articles, metadata, internal links, FAQs, and publishing cadence",
    category: "Business & Marketing",
    tags: ["seo", "content", "articles", "metadata", "premium", "remote"],
  },
  {
    name: "landing-page-pack",
    displayName: "Landing Page Pack",
    description: "Generate premium landing page packages with conversion copy, wireframes, CTA maps, experiments, preview HTML, and implementation notes",
    category: "Business & Marketing",
    tags: ["landing-page", "sales", "copywriting", "conversion", "premium", "remote"],
  },
  {
    name: "one-page-website",
    displayName: "One Page Website",
    description: "Generate hosted static one-page website bundles with HTML, CSS, JavaScript, copy, section maps, deploy notes, and manifest",
    category: "Business & Marketing",
    tags: ["website", "landing-page", "static-site", "html", "premium", "remote"],
  },
  {
    name: "ad-creative-pack",
    displayName: "Ad Creative Pack",
    description: "Generate premium paid ad packages with platform copy, creative concepts, image prompts, audience angles, and test matrices",
    category: "Business & Marketing",
    tags: ["ads", "creative", "marketing", "copywriting", "premium", "remote"],
  },
  {
    name: "email-sequence",
    displayName: "Email Sequence",
    description: "Generate premium email campaign packages with subject lines, preview text, body copy, segmentation notes, CTA variants, HTML emails, and send plans",
    category: "Business & Marketing",
    tags: ["email", "marketing", "campaign", "copywriting", "premium", "remote"],
  },
  {
    name: "social-content-calendar",
    displayName: "Social Content Calendar",
    description: "Generate premium social content calendars with daily posts, channel strategy, asset briefs, hooks, publishing schedules, and repurposing maps",
    category: "Business & Marketing",
    tags: ["social", "content", "calendar", "marketing", "premium", "remote"],
  },
  {
    name: "social-media-kit",
    displayName: "Social Media Kit",
    description: "Create social media kits with graphics, templates, and brand guidelines",
    category: "Business & Marketing",
    tags: ["social-media", "kit", "branding", "templates"],
  },
  {
    name: "sponsorship-proposal-lab",
    displayName: "Sponsorship Proposal Lab",
    description: "Create sponsorship proposals with packages, ROI projections, and benefits",
    category: "Business & Marketing",
    tags: ["sponsorship", "proposal", "marketing", "partnerships"],
  },
  {
    name: "webinar-script-coach",
    displayName: "Webinar Script Coach",
    description: "Coach and refine webinar scripts with engagement tips and flow optimization",
    category: "Business & Marketing",
    tags: ["webinar", "script", "coaching", "presentation"],
  },
];
