import type { SkillMeta } from "../registry-types.js";

export const BUSINESS_MARKETING_SKILLS: SkillMeta[] = [
  {
    name: "customer-feedback-report",
    displayName: "Customer Feedback Report",
    description: "Generate customer feedback reports with clusters, sentiment, root causes, roadmap recommendations, evidence, and PDF/Markdown artifacts",
    category: "Business & Marketing",
    kind: "instruction",
    tags: ["feedback", "customer", "sentiment", "roadmap", "report"],
  },
  {
    name: "pitch-deck",
    displayName: "Pitch Deck",
    description: "Generate investor and sales deck packages with slides, speaker notes, design direction, PDF, and PPTX artifacts",
    category: "Business & Marketing",
    kind: "instruction",
    dependencies: ["market-research-report"],
    tags: ["deck", "presentation", "investor", "sales", "pptx"],
  },
  {
    name: "proposal-pack",
    displayName: "Proposal Pack",
    description: "Generate client proposal packages with proposal, statement of work, pricing, timeline, assumptions, cover email, and PDF/Markdown artifacts",
    category: "Business & Marketing",
    kind: "instruction",
    tags: ["proposal", "sow", "sales", "pricing", "timeline"],
  },
  {
    name: "seo-content-pack",
    displayName: "SEO Content Pack",
    description: "Generate SEO content packages with topic clusters, articles, metadata, internal links, FAQs, and publishing cadence",
    category: "Business & Marketing",
    kind: "instruction",
    tags: ["seo", "content", "articles", "metadata"],
  },
  {
    name: "landing-page-pack",
    displayName: "Landing Page Pack",
    description: "Generate landing page packages with conversion copy, wireframes, CTA maps, experiments, preview HTML, and implementation notes",
    category: "Business & Marketing",
    kind: "instruction",
    tags: ["landing-page", "sales", "copywriting", "conversion"],
  },
  {
    name: "ad-creative-pack",
    displayName: "Ad Creative Pack",
    description: "Generate paid ad packages with platform copy, creative concepts, image prompts, audience angles, and test matrices",
    category: "Business & Marketing",
    kind: "instruction",
    tags: ["ads", "creative", "marketing", "copywriting"],
  },
  {
    name: "email-sequence",
    displayName: "Email Sequence",
    description: "Generate email campaign packages with subject lines, preview text, body copy, segmentation notes, CTA variants, HTML emails, and send plans",
    category: "Business & Marketing",
    kind: "instruction",
    tags: ["email", "marketing", "campaign", "copywriting"],
  },
  {
    name: "social-content-calendar",
    displayName: "Social Content Calendar",
    description: "Generate social content calendars with daily posts, channel strategy, asset briefs, hooks, publishing schedules, and repurposing maps",
    category: "Business & Marketing",
    kind: "instruction",
    tags: ["social", "content", "calendar", "marketing"],
  },
];
