import type { SkillMeta } from "../registry-types.js";

export const CONTENT_GENERATION_SKILLS: SkillMeta[] = [
  {
    name: "emoji",
    displayName: "Emoji",
    description: "Generate complete emoji packs using AI with DALL-E 3 or Gemini",
    category: "Content Generation",
    tags: ["emoji", "generation", "ai", "design"],
  },
  {
    name: "generate-diagram",
    displayName: "Generate Diagram",
    description: "Generate diagrams including flowcharts, sequence diagrams, and system architecture",
    category: "Content Generation",
    tags: ["diagrams", "flowcharts", "visualization", "architecture"],
  },
  {
    name: "doc-generate",
    displayName: "Doc Generate",
    description: "Generate DOCX documents with rich formatting, templates, and AI content",
    category: "Content Generation",
    tags: ["docx", "document", "word", "generation"],
  },
  {
    name: "excel",
    displayName: "Excel",
    description: "Generate Excel spreadsheets with data, formulas, and professional styling",
    category: "Content Generation",
    tags: ["excel", "spreadsheet", "generation", "data"],
  },
  {
    name: "pdf-generate",
    displayName: "PDF Generate",
    description: "Generate PDF documents with rich formatting and layouts",
    category: "Content Generation",
    tags: ["pdf", "document", "generation", "formatting"],
  },
  {
    name: "generate-presentation",
    displayName: "Generate Presentation",
    description: "Generate presentation decks with slides, content, and visuals",
    category: "Content Generation",
    tags: ["presentation", "slides", "deck", "generation"],
  },
  {
    name: "slide-deck-generator",
    displayName: "Slide Deck Generator",
    description: "Generate hosted slide decks from briefs, docs, or outlines with PDF, PPTX, speaker notes, and structured slide metadata",
    category: "Content Generation",
    tags: ["presentation", "slides", "deck", "documents", "premium", "remote"],
  },
  {
    name: "generate-qrcode",
    displayName: "Generate QR Code",
    description: "Generate QR codes with custom styling and embedded data",
    category: "Content Generation",
    tags: ["qrcode", "generation", "encoding", "visual"],
  },
  {
    name: "generate-resume",
    displayName: "Generate Resume",
    description: "Generate professional resumes with formatting and content optimization",
    category: "Content Generation",
    tags: ["resume", "cv", "career", "generation"],
  },
  {
    name: "image",
    displayName: "Image",
    description: "Generate images using provider-cost AI backends: OpenAI, Minimax, and Gemini",
    category: "Content Generation",
    tags: ["image", "generation", "ai", "openai", "minimax", "gemini"],
  },
  {
    name: "video",
    displayName: "Video",
    description: "Generate videos using provider-cost AI backends: OpenAI Sora, Minimax Hailuo, Gemini Veo, and Seedance",
    category: "Content Generation",
    tags: ["video", "generation", "ai", "openai", "minimax", "gemini", "seedance"],
  },
  {
    name: "audio",
    displayName: "Audio",
    description: "Generate speech and audio using provider-cost AI backends: OpenAI, Minimax, and Gemini",
    category: "Content Generation",
    tags: ["audio", "speech", "generation", "ai", "openai", "minimax", "gemini"],
  },
  {
    name: "music",
    displayName: "Music",
    description: "Generate music using provider-cost AI backends: Minimax and Gemini Lyria",
    category: "Content Generation",
    tags: ["music", "generation", "ai", "minimax", "gemini"],
  },
  {
    name: "music-album",
    displayName: "Music Album",
    description: "Generate hosted music album packages with 7, 14, or 21 songs, cover art, track metadata, manifests, receipts, and downloadable artifacts",
    category: "Content Generation",
    tags: ["music", "album", "songs", "cover-art", "premium", "remote"],
  },
  {
    name: "playlist-maker",
    displayName: "Playlist Maker",
    description: "Create a curated playlist with web research, track selection, and AI-generated album art",
    category: "Content Generation",
    tags: ["playlist", "music", "curation", "album-art", "premium"],
  },
  {
    name: "photo-album",
    displayName: "Photo Album",
    description: "Generate hosted themed photo albums with configurable image counts, style, aspect ratios, cover image, captions, gallery manifest, receipts, and downloadable assets",
    category: "Content Generation",
    tags: ["photo", "album", "image-generation", "gallery", "premium", "remote"],
  },
  {
    name: "short-video-pack",
    displayName: "Short Video Pack",
    description: "Generate hosted short-form video packs from a brief with scripts, shot lists, clips or edit packages, captions, thumbnails, manifests, and receipts",
    category: "Content Generation",
    tags: ["video", "short-form", "clips", "captions", "premium", "remote"],
  },
  {
    name: "voiceover-jingle-pack",
    displayName: "Voiceover And Jingle Pack",
    description: "Generate hosted voiceover variants and short jingles with style direction, duration, audio artifacts, usage notes, manifests, and receipts",
    category: "Content Generation",
    tags: ["audio", "voiceover", "jingle", "music", "premium", "remote"],
  },
  {
    name: "brand-photo-shoot",
    displayName: "Brand Photo Shoot",
    description: "Generate hosted product or brand photo shoot sets with prompt planning, multiple scenes, aspect ratios, gallery exports, captions, and receipts",
    category: "Content Generation",
    tags: ["brand", "photo", "product", "shoot", "premium", "remote"],
  },
];
