import type { SkillMeta } from "../registry-types.js";

export const DATA_ANALYSIS_SKILLS: SkillMeta[] = [
  {
    name: "analyze-data",
    displayName: "Analyze Data",
    description: "Data science insights for CSV and JSON datasets with statistical analysis",
    category: "Data & Analysis",
    tags: ["data", "analysis", "csv", "json", "statistics"],
  },
  {
    name: "anomaly-investigator",
    displayName: "Anomaly Investigator",
    description: "Investigate and diagnose anomalies in data, logs, and system metrics",
    category: "Data & Analysis",
    tags: ["anomaly", "investigation", "monitoring", "diagnostics"],
  },
  {
    name: "benchmark-finder",
    displayName: "Benchmark Finder",
    description: "Find industry benchmarks and performance metrics for comparison analysis",
    category: "Data & Analysis",
    tags: ["benchmark", "metrics", "industry", "comparison"],
  },
  {
    name: "dashboard-builder",
    displayName: "Dashboard Builder",
    description: "Build data dashboards with charts, metrics, and visualizations",
    category: "Data & Analysis",
    tags: ["dashboard", "visualization", "charts", "metrics"],
  },
  {
    name: "dashboard-narrator",
    displayName: "Dashboard Narrator",
    description: "Generate narrative summaries from dashboard data and metrics",
    category: "Data & Analysis",
    tags: ["dashboard", "narrative", "reporting", "insights"],
  },
  {
    name: "data-anonymizer",
    displayName: "Data Anonymizer",
    description: "Anonymize sensitive data in datasets for privacy compliance",
    category: "Data & Analysis",
    tags: ["anonymization", "privacy", "data", "compliance"],
  },
  {
    name: "dataset-health-check",
    displayName: "Dataset Health Check",
    description: "Validate dataset quality with completeness, consistency, and accuracy checks",
    category: "Data & Analysis",
    tags: ["dataset", "quality", "validation", "health-check"],
  },
  {
    name: "extract",
    displayName: "Extract",
    description: "Extract text and structured data from images, PDFs, and documents using AI",
    category: "Data & Analysis",
    tags: ["extraction", "ocr", "vision", "pdf"],
  },
  {
    name: "generate-chart",
    displayName: "Generate Chart",
    description: "Generate data charts and visualizations from datasets",
    category: "Data & Analysis",
    tags: ["charts", "visualization", "data", "graphs"],
  },
  {
    name: "kpi-digest-generator",
    displayName: "KPI Digest Generator",
    description: "Generate KPI digest reports with trends, alerts, and performance summaries",
    category: "Data & Analysis",
    tags: ["kpi", "digest", "metrics", "reporting"],
  },
  {
    name: "read-csv",
    displayName: "Read CSV",
    description: "Parse CSV files into structured JSON with delimiter and encoding detection",
    category: "Data & Analysis",
    tags: ["csv", "parsing", "tabular", "data"],
  },
  {
    name: "read-excel",
    displayName: "Read Excel",
    description: "Parse XLS and XLSX workbooks into structured JSON with sheet and formatted cell metadata",
    category: "Data & Analysis",
    tags: ["excel", "spreadsheet", "xlsx", "data"],
  },
  {
    name: "read-image",
    displayName: "Read Image",
    description: "Analyze local or remote images with Claude vision and extract visible text and visual structure",
    category: "Data & Analysis",
    tags: ["image", "vision", "ocr", "analysis"],
  },
  {
    name: "read-pdf",
    displayName: "Read PDF",
    description: "Extract text and structured content from PDF files with chunked Claude document analysis",
    category: "Data & Analysis",
    tags: ["pdf", "documents", "extraction", "analysis", "remote", "premium", "cerebras"],
  },
  {
    name: "pdf-read",
    displayName: "PDF Read",
    description: "Read multiple PDFs with page-range selection, chunked reading, and parallel processing",
    category: "Data & Analysis",
    tags: ["pdf", "reader", "extraction", "parallel", "remote", "premium", "cerebras"],
  },
  {
    name: "pdf-to-markdown",
    displayName: "PDF to Markdown",
    description: "Convert PDFs into clean markdown with remote extraction and structure cleanup",
    category: "Data & Analysis",
    tags: ["pdf", "markdown", "conversion", "remote", "premium"],
  },
  {
    name: "pdf-to-dataset",
    displayName: "PDF to Dataset",
    description: "Extract PDF tables, forms, invoices, and semi-structured content into CSV and JSON datasets",
    category: "Data & Analysis",
    tags: ["pdf", "dataset", "csv", "json", "extraction", "remote", "premium"],
  },
  {
    name: "doc-read",
    displayName: "Doc Read",
    description: "Read and extract text from DOCX files with section parsing and metadata extraction",
    category: "Data & Analysis",
    tags: ["docx", "reader", "extraction", "word"],
  },
  {
    name: "spreadsheet-cleanroom",
    displayName: "Spreadsheet Cleanroom",
    description: "Clean and sanitize spreadsheet data for analysis readiness",
    category: "Data & Analysis",
    tags: ["spreadsheet", "cleaning", "data", "sanitization"],
  },
  {
    name: "survey-insight-extractor",
    displayName: "Survey Insight Extractor",
    description: "Extract actionable insights and trends from survey response data",
    category: "Data & Analysis",
    tags: ["survey", "insights", "analysis", "data"],
  },
];
