import type { SkillMeta } from "../registry-types.js";

export const DESIGN_BRANDING_SKILLS: SkillMeta[] = [
  {
    name: "brand-assets",
    displayName: "Brand Assets",
    description: "Fetch official brand assets from a website or brand name with logos, PNG sizes, palette, typography, source metadata, and manifests",
    category: "Design & Branding",
    tags: ["brand", "logo", "assets", "palette", "typography", "premium", "remote"],
  },
  {
    name: "icon-pack",
    displayName: "Icon Pack",
    description: "Generate a coordinated set of high-quality icons delivered as SVGs and transparent PNGs",
    category: "Design & Branding",
    tags: ["icons", "icon-pack", "svg", "png", "design", "premium", "remote"],
  },
  {
    name: "logo-design",
    displayName: "Logo Design",
    description: "Generate premium multi-variant logo packages with transparent PNGs, vector-style SVGs, usage notes, and manifests",
    category: "Design & Branding",
    tags: ["logo", "design", "branding", "identity", "premium", "remote"],
  },
  {
    name: "brand-kit",
    displayName: "Brand Kit",
    description: "Generate premium brand kits with logo usage, palette, typography, brand voice, sample applications, Markdown guide, PDF guide, and SVG assets",
    category: "Design & Branding",
    tags: ["brand", "design", "palette", "typography", "premium", "remote"],
  },
  {
    name: "brand-style-guide",
    displayName: "Brand Style Guide",
    description: "Generate comprehensive brand style guides with visual identity guidelines",
    category: "Design & Branding",
    tags: ["brand", "style-guide", "identity", "design"],
  },
  {
    name: "brand-voice-audit",
    displayName: "Brand Voice Audit",
    description: "Audit content for brand voice consistency and tone alignment",
    category: "Design & Branding",
    tags: ["brand", "voice", "audit", "tone"],
  },
  {
    name: "color-palette-harmonizer",
    displayName: "Color Palette Harmonizer",
    description: "Generate harmonious color palettes for design and branding projects",
    category: "Design & Branding",
    tags: ["color", "palette", "design", "harmony"],
  },
  {
    name: "generate-book-cover",
    displayName: "Generate Book Cover",
    description: "Generate professional book cover designs with AI",
    category: "Design & Branding",
    tags: ["book-cover", "design", "generation", "publishing"],
  },
  {
    name: "generate-favicon",
    displayName: "Generate Favicon",
    description: "Generate favicons in multiple sizes and formats for websites",
    category: "Design & Branding",
    tags: ["favicon", "icon", "design", "web"],
  },
  {
    name: "microcopy-generator",
    displayName: "Microcopy Generator",
    description: "Generate UI microcopy including button text, tooltips, and error messages",
    category: "Design & Branding",
    tags: ["microcopy", "ux", "ui-text", "writing"],
  },
  {
    name: "packaging-concept-studio",
    displayName: "Packaging Concept Studio",
    description: "Design product packaging concepts with mockups and specifications",
    category: "Design & Branding",
    tags: ["packaging", "design", "product", "concept"],
  },
  {
    name: "presentation-theme-maker",
    displayName: "Presentation Theme Maker",
    description: "Create custom presentation themes with color schemes and layouts",
    category: "Design & Branding",
    tags: ["presentation", "theme", "design", "templates"],
  },
  {
    name: "print-collateral-designer",
    displayName: "Print Collateral Designer",
    description: "Design print collateral including brochures, flyers, and business cards",
    category: "Design & Branding",
    tags: ["print", "collateral", "brochures", "design"],
  },
  {
    name: "product-mockup",
    displayName: "Product Mockup",
    description: "Generate hosted product mockup packages with visual variants, prompts, usage notes, and asset metadata",
    category: "Design & Branding",
    tags: ["product", "mockup", "visualization", "marketing", "premium", "remote"],
  },
  {
    name: "testimonial-graphics",
    displayName: "Testimonial Graphics",
    description: "Create visual testimonial graphics for social proof and marketing",
    category: "Design & Branding",
    tags: ["testimonials", "graphics", "social-proof", "marketing"],
  },
  {
    name: "colorextract",
    displayName: "Color Extract",
    description: "Extract complete color palettes from screenshots and images using Claude Vision. Outputs open-styles compatible profiles.",
    category: "Design & Branding",
    tags: ["colors", "palette", "design", "vision", "screenshot", "extract", "open-styles"],
  },
  {
    name: "siteanalyze",
    displayName: "Site Analyze",
    description: "Analyze any website's design system — detects shadcn/ui, Tailwind, extracts colors, typography, and components via Playwright + Claude Vision.",
    category: "Design & Branding",
    tags: ["design", "shadcn", "tailwind", "colors", "typography", "playwright", "analysis", "open-styles"],
  },
];
