import type { SkillMeta } from "../registry-types.js";

export const DEVELOPMENT_TOOLS_SKILLS: SkillMeta[] = [
  {
    name: "repo-onboarding-report",
    displayName: "Repo Onboarding Report",
    description: "Generate repository onboarding packages with architecture maps, setup guides, risk registers, and first-week plans",
    category: "Development Tools",
    kind: "instruction",
    tags: ["repository", "onboarding", "architecture", "developer-tools"],
  },
  {
    name: "security-audit-report",
    displayName: "Security Audit Report",
    description: "Generate application security hardening reports covering auth, secrets, headers, webhooks, RLS, permissions, dependencies, and prioritized fixes",
    category: "Development Tools",
    kind: "instruction",
    tags: ["security", "audit", "hardening", "rls", "webhooks"],
  },
  {
    name: "performance-audit-report",
    displayName: "Performance Audit Report",
    description: "Generate performance audit reports with metrics, findings, budgets, remediation plans, and manifest artifacts",
    category: "Development Tools",
    kind: "instruction",
    tags: ["performance", "audit", "latency", "budget", "web"],
  },
  {
    name: "migration-plan-pack",
    displayName: "Migration Plan Pack",
    description: "Generate migration plans for frameworks, libraries, databases, infrastructure, and architecture upgrades with risk matrix, checklist, rollout, and test strategy artifacts",
    category: "Development Tools",
    kind: "instruction",
    tags: ["migration", "upgrade", "planning", "frameworks", "databases"],
  },
  {
    name: "test-suite-generator",
    displayName: "Test Suite Generator",
    description: "Generate runnable API, unit, and browser test suite packages with coverage notes",
    category: "Development Tools",
    kind: "instruction",
    tags: ["testing", "qa", "api-tests", "browser-tests", "coverage"],
  },
  {
    name: "api-test-suite",
    displayName: "API Test Suite",
    description: "Generate and run API test suites with comprehensive endpoint coverage",
    category: "Development Tools",
    tags: ["api", "testing", "automation", "qa"],
  },
  {
    name: "api-docs-portal",
    displayName: "API Docs Portal",
    description: "Generate static API documentation portals from OpenAPI specs, route lists, and endpoint examples",
    category: "Development Tools",
    tags: ["api", "documentation", "openapi", "portal"],
  },
  {
    name: "codefix",
    displayName: "Code Fix",
    description: "Code quality CLI for auto-linting, formatting, fixing, and style enforcement",
    category: "Development Tools",
    tags: ["code", "linting", "formatting", "quality"],
  },
  {
    name: "commitpush",
    displayName: "Commit Push",
    description: "Create logical commits from repo changes and push directly to the main branch",
    category: "Development Tools",
    tags: ["git", "commit", "push", "automation"],
  },
  {
    name: "commitpushpr",
    displayName: "Commit Push PR",
    description: "Create logical commits, push a feature branch, and open a GitHub pull request",
    category: "Development Tools",
    dependencies: ["commitpush"],
    tags: ["git", "commit", "pull-request", "github", "automation"],
  },
  {
    name: "database-explorer",
    displayName: "Database Explorer",
    description: "Explore and query databases with an interactive interface",
    category: "Development Tools",
    tags: ["database", "explorer", "sql", "query"],
  },
  {
    name: "diff-viewer",
    displayName: "Diff Viewer",
    description: "View and analyze file differences with visual diff representation",
    category: "Development Tools",
    tags: ["diff", "comparison", "files", "code-review"],
  },
  {
    name: "generate-api-client",
    displayName: "Generate API Client",
    description: "Generate API client libraries from OpenAPI specs and documentation",
    category: "Development Tools",
    tags: ["api", "client", "code-generation", "openapi"],
  },
  {
    name: "generate-dockerfile",
    displayName: "Generate Dockerfile",
    description: "Generate optimized Dockerfiles for containerized applications",
    category: "Development Tools",
    tags: ["docker", "dockerfile", "containers", "devops"],
  },
  {
    name: "generate-env",
    displayName: "Generate Env",
    description: "Generate environment variable files from templates and configurations",
    category: "Development Tools",
    tags: ["env", "environment", "configuration", "dotenv"],
  },
  {
    name: "generate-sitemap",
    displayName: "Generate Sitemap",
    description: "Generate XML sitemaps for websites and web applications",
    category: "Development Tools",
    tags: ["sitemap", "seo", "xml", "web"],
  },
  {
    name: "hook",
    displayName: "Hook",
    description: "Claude Code hook creation skill - generates standardized hook scaffolds",
    category: "Development Tools",
    tags: ["hooks", "scaffold", "claude-code", "automation"],
  },
  {
    name: "http-server",
    displayName: "HTTP Server",
    description: "Spin up local HTTP servers for development and testing",
    category: "Development Tools",
    tags: ["http", "server", "development", "local"],
  },
  {
    name: "lorem-generator",
    displayName: "Lorem Generator",
    description: "Generate placeholder text in various styles and lengths",
    category: "Development Tools",
    tags: ["lorem", "placeholder", "text", "mockup"],
  },
  {
    name: "managemcp",
    displayName: "Manage MCP",
    description: "Manage MCP servers with install, configure, and lifecycle operations",
    category: "Development Tools",
    tags: ["mcp", "management", "servers", "configuration"],
  },
  {
    name: "markdown-validator",
    displayName: "Markdown Validator",
    description: "Validate markdown files for syntax, links, and formatting issues",
    category: "Development Tools",
    tags: ["markdown", "validation", "linting", "formatting"],
  },
  {
    name: "monitor",
    displayName: "Monitor",
    description: "Operate the open-monitor MCP for machine health, processes, cron jobs, and cleanup workflows",
    category: "Development Tools",
    tags: ["monitoring", "mcp", "processes", "operations"],
  },
  {
    name: "regex-tester",
    displayName: "Regex Tester",
    description: "Test and validate regular expressions with sample inputs",
    category: "Development Tools",
    tags: ["regex", "testing", "validation", "patterns"],
  },
  {
    name: "scancommitpr",
    displayName: "Scan Commit PR",
    description: "Scan repo changes, group into logical commits, push, and optionally create a PR",
    category: "Development Tools",
    dependencies: ["scancommitpush"],
    tags: ["git", "commit", "push", "pull-request", "automation"],
  },
  {
    name: "scancommitpush",
    displayName: "Scan Commit Push",
    description: "Scan repo changes, group into logical commits with conventional messages, and push to GitHub",
    category: "Development Tools",
    tags: ["git", "commit", "push", "automation"],
  },
  {
    name: "security-audit",
    displayName: "Security Audit",
    description: "Perform security audits on codebases and infrastructure configurations",
    category: "Development Tools",
    tags: ["security", "audit", "vulnerabilities", "scanning"],
  },
  {
    name: "tmux-session",
    displayName: "Tmux Session",
    description: "Create and manage grouped tmux sessions with workspace-aware naming and window layout guidance",
    category: "Development Tools",
    tags: ["tmux", "terminal", "sessions", "workspace"],
  },
  {
    name: "validate-config",
    displayName: "Validate Config",
    description: "Validate configuration files for syntax and schema compliance",
    category: "Development Tools",
    tags: ["config", "validation", "schema", "linting"],
  },
];
