import type { SkillMeta } from "../registry-types.js";

export const DEVELOPMENT_TOOLS_SKILLS: SkillMeta[] = [
  {
    name: "api-test-suite",
    displayName: "API Test Suite",
    description: "Generate and run API test suites with comprehensive endpoint coverage",
    category: "Development Tools",
    tags: ["api", "testing", "automation", "qa"],
  },
  {
    name: "apidocs",
    displayName: "API Docs",
    description: "Agentic web crawler for API documentation indexing and semantic search",
    category: "Development Tools",
    tags: ["api", "documentation", "search", "indexing"],
  },
  {
    name: "api-docs-portal",
    displayName: "API Docs Portal",
    description: "Generate premium static API documentation portals from OpenAPI specs, route lists, and endpoint examples",
    category: "Development Tools",
    tags: ["api", "documentation", "openapi", "portal", "premium", "remote"],
  },
  {
    name: "sdk-generator",
    displayName: "SDK Generator",
    description: "Generate hosted TypeScript SDK scaffolds with client code, types, package files, tests, README, examples, and API summaries",
    category: "Development Tools",
    tags: ["sdk", "api", "typescript", "developer-tools", "premium", "remote"],
  },
  {
    name: "repo-onboarding-report",
    displayName: "Repo Onboarding Report",
    description: "Generate hosted repository onboarding packages with architecture maps, setup guides, risk registers, and first-week plans",
    category: "Development Tools",
    tags: ["repository", "onboarding", "architecture", "developer-tools", "premium", "remote"],
  },
  {
    name: "codefix",
    displayName: "Code Fix",
    description: "Code quality CLI for auto-linting, formatting, fixing, and style enforcement",
    category: "Development Tools",
    tags: ["code", "linting", "formatting", "quality"],
  },
  {
    name: "commitpush",
    displayName: "Commit Push",
    description: "Create logical commits from repo changes and push directly to the main branch",
    category: "Development Tools",
    tags: ["git", "commit", "push", "automation"],
  },
  {
    name: "commitpushpr",
    displayName: "Commit Push PR",
    description: "Create logical commits, push a feature branch, and open a GitHub pull request",
    category: "Development Tools",
    tags: ["git", "commit", "pull-request", "github", "automation"],
    dependencies: ["commitpush"],
  },
  {
    name: "consolelog",
    displayName: "Console Log",
    description: "Monitor console logs from web applications using Playwright headless browser",
    category: "Development Tools",
    tags: ["console", "monitoring", "debugging", "logs"],
  },
  {
    name: "database-explorer",
    displayName: "Database Explorer",
    description: "Explore and query databases with an interactive interface",
    category: "Development Tools",
    tags: ["database", "explorer", "sql", "query"],
  },
  {
    name: "deploy",
    displayName: "Deploy",
    description: "Deployment CLI for managing EC2 deployments with automated health checks",
    category: "Development Tools",
    tags: ["deployment", "ec2", "aws", "ci-cd"],
  },
  {
    name: "diff-viewer",
    displayName: "Diff Viewer",
    description: "View and analyze file differences with visual diff representation",
    category: "Development Tools",
    tags: ["diff", "comparison", "files", "code-review"],
  },
  {
    name: "generate-api-client",
    displayName: "Generate API Client",
    description: "Generate API client libraries from OpenAPI specs and documentation",
    category: "Development Tools",
    tags: ["api", "client", "code-generation", "openapi"],
  },
  {
    name: "generate-dockerfile",
    displayName: "Generate Dockerfile",
    description: "Generate optimized Dockerfiles for containerized applications",
    category: "Development Tools",
    tags: ["docker", "dockerfile", "containers", "devops"],
  },
  {
    name: "generate-documentation",
    displayName: "Generate Documentation",
    description: "Generate project documentation including READMEs, architecture docs, and API references from codebase analysis",
    category: "Development Tools",
    tags: ["documentation", "generation", "code", "docs"],
  },
  {
    name: "generate-env",
    displayName: "Generate Env",
    description: "Generate environment variable files from templates and configurations",
    category: "Development Tools",
    tags: ["env", "environment", "configuration", "dotenv"],
  },
  {
    name: "generate-mock-data",
    displayName: "Generate Mock Data",
    description: "Generate realistic mock data for testing and development",
    category: "Development Tools",
    tags: ["mock-data", "testing", "generation", "fake-data"],
  },
  {
    name: "generate-pr-description",
    displayName: "Generate PR Description",
    description: "Generate pull request descriptions from code diffs and commit history",
    category: "Development Tools",
    tags: ["pr", "github", "description", "code-review"],
  },
  {
    name: "generate-regex",
    displayName: "Generate Regex",
    description: "Generate regular expressions from natural language descriptions",
    category: "Development Tools",
    tags: ["regex", "generation", "pattern", "matching"],
  },
  {
    name: "generate-sitemap",
    displayName: "Generate Sitemap",
    description: "Generate XML sitemaps for websites and web applications",
    category: "Development Tools",
    tags: ["sitemap", "seo", "xml", "web"],
  },
  {
    name: "generate-sql",
    displayName: "Generate SQL",
    description: "Generate SQL queries and database schemas from natural language",
    category: "Development Tools",
    tags: ["sql", "database", "generation", "queries"],
  },
  {
    name: "github-manager",
    displayName: "GitHub Manager",
    description: "Manage GitHub repositories, issues, PRs, and workflows",
    category: "Development Tools",
    tags: ["github", "repository", "management", "issues"],
  },
  {
    name: "hook",
    displayName: "Hook",
    description: "Claude Code hook creation skill - generates standardized hook scaffolds",
    category: "Development Tools",
    tags: ["hooks", "scaffold", "claude-code", "automation"],
  },
  {
    name: "http-server",
    displayName: "HTTP Server",
    description: "Spin up local HTTP servers for development and testing",
    category: "Development Tools",
    tags: ["http", "server", "development", "local"],
  },
  {
    name: "lorem-generator",
    displayName: "Lorem Generator",
    description: "Generate placeholder text in various styles and lengths",
    category: "Development Tools",
    tags: ["lorem", "placeholder", "text", "mockup"],
  },
  {
    name: "managehook",
    displayName: "Manage Hook",
    description: "Manage Claude Code hooks with install, configure, and lifecycle operations",
    category: "Development Tools",
    tags: ["hooks", "management", "claude-code", "configuration"],
  },
  {
    name: "managemcp",
    displayName: "Manage MCP",
    description: "Manage MCP servers with install, configure, and lifecycle operations",
    category: "Development Tools",
    tags: ["mcp", "management", "servers", "configuration"],
  },
  {
    name: "manageskill",
    displayName: "Manage Skill",
    description: "Manage Claude Code skills with install, configure, and lifecycle operations",
    category: "Development Tools",
    tags: ["skills", "management", "claude-code", "configuration"],
  },
  {
    name: "markdown-validator",
    displayName: "Markdown Validator",
    description: "Validate markdown files for syntax, links, and formatting issues",
    category: "Development Tools",
    tags: ["markdown", "validation", "linting", "formatting"],
  },
  {
    name: "mcp-builder",
    displayName: "MCP Builder",
    description: "Build MCP server packages with standardized structure and tooling",
    category: "Development Tools",
    tags: ["mcp", "builder", "scaffold", "server"],
  },
  {
    name: "monitor",
    displayName: "Monitor",
    description: "Operate the open-monitor MCP for machine health, processes, cron jobs, and cleanup workflows",
    category: "Development Tools",
    tags: ["monitoring", "mcp", "processes", "operations"],
  },
  {
    name: "npmpublish",
    displayName: "NPM Publish",
    description: "Publish npm packages with sensible defaults: private access, patch version bumps",
    category: "Development Tools",
    tags: ["npm", "publish", "packages", "registry"],
  },
  {
    name: "regex-tester",
    displayName: "Regex Tester",
    description: "Test and validate regular expressions with sample inputs",
    category: "Development Tools",
    tags: ["regex", "testing", "validation", "patterns"],
  },
  {
    name: "scaffold-project",
    displayName: "Scaffold Project",
    description: "Scaffold new projects with standardized structure and boilerplate",
    category: "Development Tools",
    tags: ["scaffold", "project", "boilerplate", "template"],
  },
  {
    name: "scancommitpr",
    displayName: "Scan Commit PR",
    description: "Scan repo changes, group into logical commits, push, and optionally create a PR",
    category: "Development Tools",
    tags: ["git", "commit", "push", "pull-request", "automation"],
    dependencies: ["scancommitpush"],
  },
  {
    name: "scancommitpush",
    displayName: "Scan Commit Push",
    description: "Scan repo changes, group into logical commits with conventional messages, and push to GitHub",
    category: "Development Tools",
    tags: ["git", "commit", "push", "automation"],
  },
  {
    name: "security-audit",
    displayName: "Security Audit",
    description: "Perform security audits on codebases and infrastructure configurations",
    category: "Development Tools",
    tags: ["security", "audit", "vulnerabilities", "scanning"],
  },
  {
    name: "security-audit-report",
    displayName: "Security Audit Report",
    description: "Generate premium SaaS security hardening reports covering auth, secrets, headers, webhooks, RLS, permissions, dependencies, and prioritized fixes",
    category: "Development Tools",
    tags: ["security", "audit", "hardening", "rls", "webhooks", "premium", "remote"],
  },
  {
    name: "performance-audit-report",
    displayName: "Performance Audit Report",
    description: "Generate premium performance audit reports with metrics, findings, budgets, remediation plans, and manifest artifacts",
    category: "Development Tools",
    tags: ["performance", "audit", "latency", "budget", "web", "premium", "remote"],
  },
  {
    name: "migration-plan-pack",
    displayName: "Migration Plan Pack",
    description: "Generate premium migration plans for frameworks, libraries, databases, infrastructure, and architecture upgrades with risk matrix, checklist, rollout, and test strategy artifacts",
    category: "Development Tools",
    tags: ["migration", "upgrade", "planning", "frameworks", "databases", "premium", "remote"],
  },
  {
    name: "terraform-generator",
    displayName: "Terraform Generator",
    description: "Generate Terraform infrastructure-as-code configurations",
    category: "Development Tools",
    tags: ["terraform", "iac", "infrastructure", "devops"],
  },
  {
    name: "tmux-session",
    displayName: "Tmux Session",
    description: "Create and manage grouped tmux sessions with workspace-aware naming and window layout guidance",
    category: "Development Tools",
    tags: ["tmux", "terminal", "sessions", "workspace"],
  },
  {
    name: "test-suite-generator",
    displayName: "Test Suite Generator",
    description: "Generate premium runnable API, unit, and browser test suite packages with coverage notes",
    category: "Development Tools",
    tags: ["testing", "qa", "api-tests", "browser-tests", "coverage", "premium", "remote"],
  },
  {
    name: "validate-config",
    displayName: "Validate Config",
    description: "Validate configuration files for syntax and schema compliance",
    category: "Development Tools",
    tags: ["config", "validation", "schema", "linting"],
  },
  {
    name: "supabase-query-review",
    displayName: "Supabase Query Review",
    description: "Review Supabase queries, RLS policies, and Postgres access patterns for security issues. Windows / PowerShell / cmd. Tags: supabase, postgres, sql. Use when supabase rls, postgres security review, sql injection supabase, row level security audit.",
    category: "Development Tools",
    tags: ["supabase", "postgres", "sql", "security", "rls", "database", "audit", "hardening"],
  },
];
