import type { SkillMeta } from "../registry-types.js";

export const FINANCE_COMPLIANCE_SKILLS: SkillMeta[] = [
  {
    name: "budget-variance-analyzer",
    displayName: "Budget Variance Analyzer",
    description: "Analyze budget versus actual spending with variance reporting",
    category: "Finance & Compliance",
    tags: ["budget", "variance", "analysis", "finance"],
  },
  {
    name: "compliance-copy-check",
    displayName: "Compliance Copy Check",
    description: "Check marketing copy for regulatory compliance and legal requirements",
    category: "Finance & Compliance",
    tags: ["compliance", "copy", "legal", "regulatory"],
  },
  {
    name: "compliance-report-pack",
    displayName: "Compliance Report Pack",
    description: "Generate compliance report packages for regulatory submissions",
    category: "Finance & Compliance",
    tags: ["compliance", "reporting", "regulatory", "audit"],
  },
  {
    name: "contract-plainlanguage",
    displayName: "Contract Plain Language",
    description: "Convert legal contracts into plain language summaries for easy understanding",
    category: "Finance & Compliance",
    tags: ["contract", "legal", "plain-language", "summary"],
  },
  {
    name: "contract-review-report",
    displayName: "Contract Review Report",
    description: "Generate premium contract review reports with risk register, clause summary, redline suggestions, negotiation email, and manifest artifacts",
    category: "Finance & Compliance",
    tags: ["contract", "legal", "review", "risk", "premium", "remote"],
  },
  {
    name: "extract-invoice",
    displayName: "Extract Invoice",
    description: "Extract structured data from invoice documents using AI",
    category: "Finance & Compliance",
    tags: ["invoice", "extraction", "ocr", "finance"],
  },
  {
    name: "forecast-scenario-lab",
    displayName: "Forecast Scenario Lab",
    description: "Model business forecast scenarios with multiple variable assumptions",
    category: "Finance & Compliance",
    tags: ["forecast", "scenarios", "modeling", "planning"],
  },
  {
    name: "grant-application-drafter",
    displayName: "Grant Application Drafter",
    description: "Draft grant applications with structured proposals and budgets",
    category: "Finance & Compliance",
    tags: ["grants", "application", "drafting", "funding"],
  },
  {
    name: "invoice",
    displayName: "Invoice",
    description: "Generate professional invoices with company management and PDF export",
    category: "Finance & Compliance",
    tags: ["invoice", "billing", "pdf", "finance"],
  },
  {
    name: "invoice-dispute-helper",
    displayName: "Invoice Dispute Helper",
    description: "Assist with invoice disputes by analyzing charges and generating responses",
    category: "Finance & Compliance",
    tags: ["invoice", "dispute", "resolution", "billing"],
  },
  {
    name: "invoice-reconciliation",
    displayName: "Invoice Reconciliation",
    description: "Generate premium invoice reconciliation reports with matched payments, discrepancies, anomaly notes, summaries, and manifest artifacts",
    category: "Finance & Compliance",
    tags: ["invoice", "payments", "reconciliation", "finance", "premium", "remote"],
  },
  {
    name: "payroll-change-prepper",
    displayName: "Payroll Change Prepper",
    description: "Prepare payroll change documentation and calculations",
    category: "Finance & Compliance",
    tags: ["payroll", "changes", "hr", "finance"],
  },
  {
    name: "procurement-scorecard",
    displayName: "Procurement Scorecard",
    description: "Generate procurement scorecards for vendor evaluation and comparison",
    category: "Finance & Compliance",
    tags: ["procurement", "scorecard", "vendor", "evaluation"],
  },
  {
    name: "proposal-redline-advisor",
    displayName: "Proposal Redline Advisor",
    description: "Review and redline proposals with suggested edits and negotiations",
    category: "Finance & Compliance",
    tags: ["proposal", "redline", "review", "negotiation"],
  },
  {
    name: "risk-disclosure-kit",
    displayName: "Risk Disclosure Kit",
    description: "Generate risk disclosure documents and compliance statements",
    category: "Finance & Compliance",
    tags: ["risk", "disclosure", "compliance", "legal"],
  },
  {
    name: "roi-comparison-tool",
    displayName: "ROI Comparison Tool",
    description: "Compare return on investment across different options and scenarios",
    category: "Finance & Compliance",
    tags: ["roi", "comparison", "investment", "analysis"],
  },
  {
    name: "subscription-spend-watcher",
    displayName: "Subscription Spend Watcher",
    description: "Track and analyze subscription spending with alerts and optimization tips",
    category: "Finance & Compliance",
    tags: ["subscription", "spending", "tracking", "optimization"],
  },
  {
    name: "timesheet",
    displayName: "Timesheet",
    description: "Generate employee timesheets with multi-profile support",
    category: "Finance & Compliance",
    tags: ["timesheet", "hours", "tracking", "payroll"],
  },
];
