import type { SkillMeta } from "../registry-types.js";

export const RESEARCH_WRITING_SKILLS: SkillMeta[] = [
  {
    name: "blog-topic-cluster",
    displayName: "Blog Topic Cluster",
    description: "Generate topic clusters and content strategies for blog SEO planning",
    category: "Research & Writing",
    tags: ["blog", "seo", "topics", "content-strategy"],
  },
  {
    name: "copytone-translator",
    displayName: "Copy Tone Translator",
    description: "Translate copy between different tones and writing styles",
    category: "Research & Writing",
    tags: ["copywriting", "tone", "translation", "style"],
  },
  {
    name: "blog-article",
    displayName: "Blog Article",
    description: "Create SEO-optimized blog article artifact packages through the self-hosted runtime",
    category: "Research & Writing",
    kind: "instruction",
    tags: ["blog", "article", "writing", "seo"],
  },
  {
    name: "market-research-report",
    displayName: "Market Research Report",
    description: "Generate market research packages with competitor tables, positioning, pricing notes, source notes, and PDF/Markdown artifacts",
    category: "Research & Writing",
    kind: "instruction",
    tags: ["market-research", "competitors", "positioning", "pricing", "report"],
  },
  {
    name: "create-ebook",
    displayName: "Create eBook",
    description: "Create complete eBooks with chapters, formatting, and cover design",
    category: "Research & Writing",
    tags: ["ebook", "writing", "publishing", "content"],
  },
  {
    name: "faq-packager",
    displayName: "FAQ Packager",
    description: "Package and organize frequently asked questions into structured documents",
    category: "Research & Writing",
    tags: ["faq", "documentation", "knowledge-base", "content"],
  },
  {
    name: "longform-structurer",
    displayName: "Longform Structurer",
    description: "Structure long-form content with outlines, chapters, and sections",
    category: "Research & Writing",
    tags: ["longform", "structure", "outline", "writing"],
  },
  {
    name: "podcast-show-notes",
    displayName: "Podcast Show Notes",
    description: "Generate podcast show notes with timestamps, summaries, and links",
    category: "Research & Writing",
    tags: ["podcast", "show-notes", "summary", "content"],
  },
  {
    name: "press-release-drafter",
    displayName: "Press Release Drafter",
    description: "Draft professional press releases for announcements and media distribution",
    category: "Research & Writing",
    tags: ["press-release", "pr", "media", "writing"],
  },
  {
    name: "write",
    displayName: "Write",
    description: "Write short or long-form content - articles, books, documentation at scale",
    category: "Research & Writing",
    tags: ["writing", "content", "articles", "documentation"],
  },
];
