import type { AnalysisReport } from './types';

export function formatMarkdown(report: AnalysisReport): string {
  let md = '# Data Analysis Report\n\n';

  md += `**Generated**: ${report.overview.timestamp}  \n`;
  md += `**Processing Time**: ${report.overview.processingTime}ms\n\n`;

  // Overview
  md += '## Dataset Overview\n\n';
  md += `- **File**: ${report.overview.fileName}\n`;
  md += `- **Size**: ${report.overview.fileSize}\n`;
  md += `- **Type**: ${report.overview.fileType}\n`;
  md += `- **Rows**: ${report.overview.rowCount.toLocaleString()}\n`;
  md += `- **Columns**: ${report.overview.columnCount}\n`;
  md += `- **Memory Usage**: ${report.overview.memoryUsage}\n\n`;

  // Column Analysis
  md += '## Column Analysis\n\n';

  report.columns.forEach(col => {
    md += `### ${col.name}\n\n`;
    md += `- **Type**: ${col.dataType}\n`;
    md += `- **Count**: ${col.count.toLocaleString()}\n`;
    md += `- **Null**: ${col.nullCount} (${col.nullPercentage}%)\n`;
    md += `- **Unique**: ${col.uniqueCount} (${col.uniquePercentage}%)\n`;
    md += `- **Sample**: ${col.sampleValues.join(', ')}\n`;

    if (col.dataType === 'numeric') {
      md += '\n**Statistics**:\n\n';
      md += `| Metric | Value |\n`;
      md += `|--------|-------|\n`;
      md += `| Mean | ${col.mean} |\n`;
      md += `| Median | ${col.median} |\n`;
      md += `| Std Dev | ${col.stdDev} |\n`;
      md += `| Min | ${col.min} |\n`;
      md += `| Max | ${col.max} |\n`;
      md += `| Q1 | ${col.q1} |\n`;
      md += `| Q3 | ${col.q3} |\n`;

      if (col.outliers && col.outliers.length > 0) {
        md += `\n**Outliers**: ${col.outliers.length} detected\n`;
      }
    }

    if (col.topValues && col.topValues.length > 0) {
      md += '\n**Top Values**:\n\n';
      md += `| Value | Count | Percentage |\n`;
      md += `|-------|-------|------------|\n`;
      col.topValues.forEach(tv => {
        md += `| ${tv.value} | ${tv.count} | ${tv.percentage}% |\n`;
      });
    }

    md += '\n';
  });

  // Correlations
  if (report.correlationPairs && report.correlationPairs.length > 0) {
    md += '## Correlation Analysis\n\n';
    md += '**Strong Correlations** (|r| > 0.5):\n\n';
    md += `| Column 1 | Column 2 | Correlation |\n`;
    md += `|----------|----------|-------------|\n`;
    report.correlationPairs.forEach(pair => {
      md += `| ${pair.col1} | ${pair.col2} | ${pair.correlation} |\n`;
    });
    md += '\n';
  }

  // Data Quality
  md += '## Data Quality\n\n';
  md += `- **Quality Score**: ${report.quality.dataQualityScore}/100\n`;
  md += `- **Missing Cells**: ${report.quality.missingCells} (${report.quality.missingPercentage}%)\n`;
  md += `- **Duplicate Rows**: ${report.quality.duplicateRows} (${report.quality.duplicatePercentage}%)\n\n`;

  if (report.quality.issues.length > 0) {
    md += '**Issues Found**:\n\n';
    report.quality.issues.forEach(issue => {
      md += `- ${issue}\n`;
    });
    md += '\n';
  }

  // Visualization Recommendations
  if (report.visualizationRecommendations.length > 0) {
    md += '## Visualization Recommendations\n\n';
    md += `| Column | Chart Type | Reason |\n`;
    md += `|--------|------------|--------|\n`;
    report.visualizationRecommendations.forEach(rec => {
      md += `| ${rec.column} | ${rec.chartType} | ${rec.reason} |\n`;
    });
    md += '\n';
  }

  // Insights
  if (report.insights.length > 0) {
    md += '## Key Insights\n\n';
    report.insights.forEach((insight, idx) => {
      md += `${idx + 1}. ${insight}\n`;
    });
    md += '\n';
  }

  md += '---\n\n';
  md += '*Generated by skills.md/analyze-data*\n';

  return md;
}

export function formatHTML(report: AnalysisReport): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Data Analysis Report - ${report.overview.fileName}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            background: #f5f5f5;
            padding: 20px;
        }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 40px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { color: #2563eb; border-bottom: 3px solid #2563eb; padding-bottom: 10px; margin-bottom: 20px; }
        h2 { color: #1e40af; margin-top: 30px; margin-bottom: 15px; border-left: 4px solid #2563eb; padding-left: 10px; }
        h3 { color: #3b82f6; margin-top: 20px; margin-bottom: 10px; }
        .meta { color: #666; font-size: 14px; margin-bottom: 30px; }
        .overview { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-bottom: 30px; }
        .overview-item { background: #f8fafc; padding: 15px; border-radius: 6px; border-left: 3px solid #2563eb; }
        .overview-item strong { display: block; color: #1e40af; margin-bottom: 5px; }
        table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }
        th { background: #f8fafc; color: #1e40af; font-weight: 600; }
        tr:hover { background: #f8fafc; }
        .quality-score { font-size: 48px; font-weight: bold; color: #10b981; text-align: center; margin: 20px 0; }
        .quality-score.medium { color: #f59e0b; }
        .quality-score.low { color: #ef4444; }
        .issue { background: #fef2f2; border-left: 3px solid #ef4444; padding: 10px; margin: 5px 0; border-radius: 4px; }
        .insight { background: #f0f9ff; border-left: 3px solid #3b82f6; padding: 10px; margin: 5px 0; border-radius: 4px; }
        .column-card { background: #fafafa; padding: 20px; margin: 15px 0; border-radius: 6px; border: 1px solid #e5e7eb; }
        .badge { display: inline-block; padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: 600; margin-right: 5px; }
        .badge.numeric { background: #dbeafe; color: #1e40af; }
        .badge.string { background: #fce7f3; color: #9f1239; }
        .badge.date { background: #d1fae5; color: #065f46; }
        .badge.boolean { background: #fef3c7; color: #92400e; }
        footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #666; font-size: 14px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>📊 Data Analysis Report</h1>
        <div class="meta">
            Generated: ${report.overview.timestamp} | Processing Time: ${report.overview.processingTime}ms
        </div>

        <h2>Dataset Overview</h2>
        <div class="overview">
            <div class="overview-item"><strong>File</strong>${report.overview.fileName}</div>
            <div class="overview-item"><strong>Size</strong>${report.overview.fileSize}</div>
            <div class="overview-item"><strong>Type</strong>${report.overview.fileType}</div>
            <div class="overview-item"><strong>Rows</strong>${report.overview.rowCount.toLocaleString()}</div>
            <div class="overview-item"><strong>Columns</strong>${report.overview.columnCount}</div>
            <div class="overview-item"><strong>Memory</strong>${report.overview.memoryUsage}</div>
        </div>

        <h2>Data Quality</h2>
        <div class="quality-score ${report.quality.dataQualityScore >= 70 ? '' : report.quality.dataQualityScore >= 50 ? 'medium' : 'low'}">
            ${report.quality.dataQualityScore}/100
        </div>
        <table>
            <tr><th>Metric</th><th>Value</th></tr>
            <tr><td>Missing Cells</td><td>${report.quality.missingCells} (${report.quality.missingPercentage}%)</td></tr>
            <tr><td>Duplicate Rows</td><td>${report.quality.duplicateRows} (${report.quality.duplicatePercentage}%)</td></tr>
        </table>
        ${report.quality.issues.length > 0 ? `
            <h3>Issues Found</h3>
            ${report.quality.issues.map(issue => `<div class="issue">${issue}</div>`).join('')}
        ` : ''}

        <h2>Column Analysis</h2>
        ${report.columns.map(col => `
            <div class="column-card">
                <h3>${col.name} <span class="badge ${col.dataType}">${col.dataType}</span></h3>
                <table>
                    <tr><td><strong>Count</strong></td><td>${col.count.toLocaleString()}</td></tr>
                    <tr><td><strong>Null</strong></td><td>${col.nullCount} (${col.nullPercentage}%)</td></tr>
                    <tr><td><strong>Unique</strong></td><td>${col.uniqueCount} (${col.uniquePercentage}%)</td></tr>
                    ${col.dataType === 'numeric' ? `
                        <tr><td><strong>Mean</strong></td><td>${col.mean}</td></tr>
                        <tr><td><strong>Median</strong></td><td>${col.median}</td></tr>
                        <tr><td><strong>Std Dev</strong></td><td>${col.stdDev}</td></tr>
                        <tr><td><strong>Min / Max</strong></td><td>${col.min} / ${col.max}</td></tr>
                        <tr><td><strong>Q1 / Q3</strong></td><td>${col.q1} / ${col.q3}</td></tr>
                    ` : ''}
                </table>
            </div>
        `).join('')}

        ${report.correlationPairs && report.correlationPairs.length > 0 ? `
            <h2>Correlation Analysis</h2>
            <table>
                <tr><th>Column 1</th><th>Column 2</th><th>Correlation</th></tr>
                ${report.correlationPairs.map(pair => `
                    <tr><td>${pair.col1}</td><td>${pair.col2}</td><td>${pair.correlation}</td></tr>
                `).join('')}
            </table>
        ` : ''}

        ${report.visualizationRecommendations.length > 0 ? `
            <h2>Visualization Recommendations</h2>
            <table>
                <tr><th>Column</th><th>Chart Type</th><th>Reason</th></tr>
                ${report.visualizationRecommendations.map(rec => `
                    <tr><td>${rec.column}</td><td>${rec.chartType}</td><td>${rec.reason}</td></tr>
                `).join('')}
            </table>
        ` : ''}

        ${report.insights.length > 0 ? `
            <h2>Key Insights</h2>
            ${report.insights.map(insight => `<div class="insight">${insight}</div>`).join('')}
        ` : ''}

        <footer>
            Generated by <strong>skills.md/analyze-data</strong>
        </footer>
    </div>
</body>
</html>`;
}

// ============================================================================
