/** Read-only admission check for a prospective Claude plugin installation.
 * This validates a frozen candidate and the current Skills/native preimages;
 * it does not call Claude, write settings, install a marketplace, or claim that
 * Claude's installer is atomic or recoverable after a crash.
 */
import { createHash } from "node:crypto";
import { lstatSync, readFileSync, readdirSync, realpathSync } from "node:fs";
import { basename, dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { isDeepStrictEqual } from "node:util";
import { assertProjectDiscovery, resolveAgentDiscovery, verifyAgentDiscovery, type ReviewedDiscoveryInputs } from "./agent-discovery.js";
import { canonicalAgentPath, recheckRootAliases, type AgentRootAlias } from "./agent-integration.js";
import { captureClaudeMarketplaceEntry } from "./claude-marketplace-entry-witness.js";
import { hashClaudePluginManifest } from "./claude-plugin-manifest-witness.js";
import { readManagedSkillPolicySnapshot } from "./managed-policy.js";
import { hashExecutableFile } from "./codex-native-skill-policy.js";

export const CLAUDE_PROSPECTIVE_REVIEW_SCHEMA = "skills.claude-plugin-prospective-review/v1" as const;
const SHA256 = /^[a-f0-9]{64}$/;
const MAX_CANDIDATE_FILES = 16_384;
const MAX_CANDIDATE_BYTES = 256 * 1024 * 1024;
const sha = (data: string | Buffer) => createHash("sha256").update(data).digest("hex");
function refuse(reason: string): never { throw new Error(`CLAUDE_CANDIDATE_REVIEW_REFUSED: ${reason}`); }
const GENERATED_MARKETPLACE_TIME = Object.freeze({ $generated: "claude-utc-timestamp", field: "known-marketplaces.lastUpdated" });
const GENERATED_FRESH_PLUGIN_INSTALLED_AT = Object.freeze({ $generated: "claude-utc-timestamp", field: "installed_plugins.fresh-row.installedAt" });
const GENERATED_PLUGIN_UPDATE_TIME = Object.freeze({ $generated: "claude-utc-timestamp", field: "installed_plugins.selected-row.lastUpdated" });
function preserveOrGenerateTimestamp(previous: string, field: string): Record<string, unknown> {
  return { $allowed: [previous, { $generated: "claude-utc-timestamp", field }] };
}

export interface ClaudeProspectiveReviewRequest {
  schema: typeof CLAUDE_PROSPECTIVE_REVIEW_SCHEMA;
  scope: { kind: "user" | "project"; projectPath: string };
  native: { home: string; executable: { path: string; target: string; version: string; sha256: string }; configRoot: string; pluginRoot: string };
  skills: { dataDir: string; policySha256: string; discoverySha256: string; discoveryInputs: ReviewedDiscoveryInputs };
  candidate: { marketplace: string; plugin: string; root: string; catalogPath: string; catalogSha256: string; closureSha256: string; manifestPath: string; manifestSha256: string };
  preimages: {
    settings: { path: string; sha256: string | null };
    userSettings: { path: string; sha256: string | null };
    projectSettings: { path: string; sha256: string | null };
    projectSettingsLocal: { path: string; sha256: string | null };
    marketplaces: { path: string; sha256: string | null };
    installedPlugins: { path: string; sha256: string | null };
  };
  /** Complete semantic documents expected after native adoption. The one
   * timestamps generated by Claude for the owned marketplace and registration
   * rows use exact typed field markers documented below; every other field is
   * concrete. */
  delta: {
    settingsAfter: Record<string, unknown>;
    knownMarketplacesAfter: Record<string, unknown>;
    installedPluginsAfter: Record<string, unknown>;
  };
  review: { pluginHooks: "reviewed-no-skill-injection" };
}

export interface ClaudeProspectiveReviewReceipt {
  schema: typeof CLAUDE_PROSPECTIVE_REVIEW_SCHEMA;
  accepted: true;
  applied: false;
  scope: ClaudeProspectiveReviewRequest["scope"];
  pluginId: string;
  native: { executablePath: string; executableTarget: string; executableVersion: string; executableSha256: string; configRoot: string; pluginRoot: string };
  candidate: { marketplace: string; plugin: string; closureSha256: string; catalogSha256: string; manifestSha256: string };
  targetSettingsPath: string;
  skillsDiscoverySha256: string;
  requestFileSha256: string;
  semanticDocumentsSha256: string;
  operationSha256: string;
  expectedPostStateSha256: string;
  preimages: Array<{ name: string; path: string; sha256: string | null }>;
  ownedDelta: { settingsEnabledPlugin: string; knownMarketplace: string; installedPlugin: string; unrelatedGraph: "preserved-by-complete-semantic-documents" };
  identityPrecondition: "Harnesses must resolve the installed Claude home/config/plugin roots and executable path/version/hash plus the installed Skills data directory through their package-owned consumers, then compare every value before trusting this receipt; this validator checks supplied paths and current bytes only and does not establish actual consumer identity";
  reviewPrecondition: "The caller's no-skill-injection assessment is bound to the raw request hash; structural checks are not semantic hook review, and Harnesses must retain its existing review record and verify the exact candidate binding";
  limitation: "validation-only; native installer atomicity and crash recovery are not established";
}

function object(value: unknown): value is Record<string, any> { return !!value && typeof value === "object" && !Array.isArray(value); }
/** Semantic digests use JSON.stringify primitives and array order, with every
 * object recursively key-sorted by ECMAScript UTF-16 code-unit order, encoded
 * as UTF-8. The request file itself is separately bound by raw bytes. */
function canonicalJson(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`;
  if (object(value)) return `{${Object.keys(value).sort().map(key => `${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(",")}}`;
  return JSON.stringify(value)!;
}
function keys(value: unknown, expected: readonly string[], name: string): asserts value is Record<string, any> {
  if (!object(value) || Object.keys(value).sort().join("\0") !== [...expected].sort().join("\0")) refuse(`${name} has an unsupported shape`);
}
function abs(path: unknown, name: string): asserts path is string {
  if (typeof path !== "string" || !path || path.length > 4096 || /[\x00-\x1f\x7f]/.test(path) || !isAbsolute(path) || resolve(path) !== path) refuse(`${name} must be a normalized absolute path`);
}
function validUtcTimestamp(value: unknown): value is string {
  return typeof value === "string" && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value)
    && Number.isFinite(Date.parse(value)) && new Date(Date.parse(value)).toISOString() === value;
}
function safeFile(path: string, name: string): Buffer {
  abs(path, name);
  for (let at = dirname(path); ; at = dirname(at)) {
    const stat = lstatSync(at, { throwIfNoEntry: false });
    if (!stat?.isDirectory() || stat.isSymbolicLink()) refuse(`${name} traverses a symlink or non-directory`);
    if (at === dirname(at)) break;
  }
  const stat = lstatSync(path, { throwIfNoEntry: false });
  if (!stat?.isFile() || stat.isSymbolicLink() || stat.size > MAX_CANDIDATE_BYTES) refuse(`${name} is not a bounded regular file`);
  return readFileSync(path);
}
function canonicalDir(path: unknown, name: string): asserts path is string {
  abs(path, name);
  if (realpathSync(path) !== path || !lstatSync(path).isDirectory()) refuse(`${name} is not a canonical directory`);
  for (let at = path; ; at = dirname(at)) {
    const stat = lstatSync(at);
    if (!stat.isDirectory() || stat.isSymbolicLink()) refuse(`${name} traverses a symlink`);
    if (at === dirname(at)) break;
  }
}

/** Fingerprint every file byte and directory name under the frozen candidate.
 * Symlinks and special files refuse; the digest binds the complete closure. */
export function captureClaudeProspectiveCandidateClosure(root: string): string {
  canonicalDir(root, "candidate root");
  const entries: Array<[string, "directory" | "file", string | null]> = [];
  let bytes = 0;
  const walk = (directory: string): void => {
    const beforeDirectory = lstatSync(directory);
    const names = readdirSync(directory).sort();
    if (new Set(names).size !== names.length) refuse("candidate contains ambiguous directory entries");
    for (const name of names) {
      if (!name || name === "." || name === ".." || name.includes("/") || name.includes("\\") || /[\x00-\x1f\x7f]/.test(name)) refuse("candidate contains an unsupported path member");
      const path = join(directory, name), rel = relative(root, path).split(sep).join("/");
      if (entries.length >= MAX_CANDIDATE_FILES) refuse("candidate closure exceeds its member limit");
      const stat = lstatSync(path);
      if (stat.isSymbolicLink()) refuse("candidate closure contains a symlink");
      if (stat.isDirectory()) { entries.push([rel, "directory", null]); walk(path); }
      else if (stat.isFile()) {
        bytes += stat.size;
        if (bytes > MAX_CANDIDATE_BYTES) refuse("candidate closure exceeds its byte limit");
        const content = safeFile(path, "candidate member"), after = lstatSync(path);
        if (!after.isFile() || after.dev !== stat.dev || after.ino !== stat.ino || after.size !== stat.size || after.mtimeMs !== stat.mtimeMs || after.ctimeMs !== stat.ctimeMs) refuse("candidate member changed while being read");
        entries.push([rel, "file", sha(content)]);
      } else refuse("candidate closure contains a special file");
    }
    const afterDirectory = lstatSync(directory);
    if (!afterDirectory.isDirectory() || afterDirectory.dev !== beforeDirectory.dev || afterDirectory.ino !== beforeDirectory.ino || afterDirectory.mtimeMs !== beforeDirectory.mtimeMs || afterDirectory.ctimeMs !== beforeDirectory.ctimeMs) refuse("candidate directory changed while being read");
  };
  walk(root);
  entries.sort((a, b) => a[0].localeCompare(b[0]));
  return sha(JSON.stringify(entries));
}

function readWitness(path: string, expected: string | null, name: string): void {
  abs(path, `${name} path`);
  const stat = lstatSync(path, { throwIfNoEntry: false });
  if (expected === null) {
    if (stat) refuse(`${name} was absent at review but is now present`);
    return;
  }
  if (!SHA256.test(expected)) refuse(`${name} has an invalid SHA-256`);
  if (!stat?.isFile() || stat.isSymbolicLink() || sha(safeFile(path, name)) !== expected) refuse(`${name} preimage changed`);
}

function jsonFile(path: string, name: string): Record<string, any> | null {
  const stat = lstatSync(path, { throwIfNoEntry: false });
  if (!stat) return null;
  let value: unknown;
  try { value = JSON.parse(safeFile(path, name).toString("utf8")); } catch { refuse(`${name} is not valid JSON`); }
  if (!object(value)) refuse(`${name} must be a JSON object`);
  return value as Record<string, any>;
}

/** Keep the explicit caller assessment from silently admitting native skill
 * payloads. This structural refusal scan is not a semantic review of hook
 * behavior; Harnesses retains and checks its existing review record against
 * this exact candidate. Claude marketplace/plugin components that declare skills or
 * commands refuse here; agent markdown retains the existing `skills:` preload
 * check used by plugin projection. Other executable components remain bound
 * by the full reviewed closure and the explicit hook assessment. */
function assertNoUnprojectedSkillPayload(root: string, catalogPath: string, marketplace: string, plugin: string, manifest: Record<string, any>): void {
  if (manifest.skills !== undefined || manifest.commands !== undefined) refuse("candidate plugin declares native skill or command payloads; project those through the Skills plugin admission flow first");
  let catalog: unknown;
  try { catalog = JSON.parse(safeFile(catalogPath, "candidate catalog").toString("utf8")); } catch { refuse("candidate catalog is not valid JSON"); }
  if (!object(catalog) || catalog.name !== marketplace || !Array.isArray(catalog.plugins)) refuse("candidate catalog identity is invalid");
  const entries = catalog.plugins.filter((entry: unknown) => object(entry) && entry.name === plugin);
  if (entries.length !== 1 || !object(entries[0])) refuse("candidate catalog plugin entry is missing or ambiguous");
  if (entries[0].skills !== undefined || entries[0].commands !== undefined) refuse("candidate marketplace entry declares native skill or command payloads");
  const walk = (directory: string): void => {
    for (const name of readdirSync(directory).sort()) {
      const path = join(directory, name), rel = relative(root, path).split(sep).join("/");
      const stat = lstatSync(path);
      if (stat.isDirectory()) walk(path);
      else if (stat.isFile()) {
        const parts = rel.toLowerCase().split("/");
        if (parts.includes("skills") || parts.includes("commands") || name.toLowerCase() === "skill.md") refuse("candidate closure contains native skill or command payload paths");
        if (parts.includes("agents") && /\.md$/i.test(name)) {
          let text: string;
          try { text = new TextDecoder("utf-8", { fatal: true }).decode(safeFile(path, "candidate agent file")); }
          catch { refuse("candidate agent file is not strict UTF-8"); }
          if (/^skills\s*:/m.test(text!)) refuse("candidate agent preloads native skills; project it through the Skills plugin admission flow first");
        }
      }
    }
  };
  walk(root);
}

/** Validate a frozen candidate review against the current filesystem. This is
 * intentionally a planner only: its receipt is not native-install authority. */
export function reviewClaudeProspectiveCandidate(request: ClaudeProspectiveReviewRequest, requestFileSha256: string): ClaudeProspectiveReviewReceipt {
  if (!SHA256.test(requestFileSha256)) refuse("request file SHA-256 is invalid");
  keys(request, ["schema", "scope", "native", "skills", "candidate", "preimages", "delta", "review"], "request");
  if (request.schema !== CLAUDE_PROSPECTIVE_REVIEW_SCHEMA) refuse("unsupported schema");
  keys(request.scope, ["kind", "projectPath"], "scope");
  if (request.scope.kind !== "user" && request.scope.kind !== "project") refuse("scope must be user or project");
  abs(request.scope.projectPath, "project path"); canonicalDir(request.scope.projectPath, "project path");
  keys(request.native, ["home", "executable", "configRoot", "pluginRoot"], "native identity");
  canonicalDir(request.native.home, "Claude home"); abs(request.native.configRoot, "Claude config root");
  keys(request.native.executable, ["path", "target", "version", "sha256"], "Claude executable identity");
  abs(request.native.executable.path, "Claude executable path"); abs(request.native.executable.target, "Claude executable target");
  if (typeof request.native.executable.version !== "string" || !request.native.executable.version || request.native.executable.version.length > 256 || /[\x00-\x1f\x7f]/.test(request.native.executable.version)
    || !SHA256.test(request.native.executable.sha256) || realpathSync(request.native.executable.path) !== request.native.executable.target
    || hashExecutableFile(request.native.executable.target) !== request.native.executable.sha256) refuse("Claude executable identity changed");
  keys(request.skills, ["dataDir", "policySha256", "discoverySha256", "discoveryInputs"], "Skills preimage"); abs(request.skills.dataDir, "Skills data directory");
  if (!SHA256.test(request.skills.policySha256) || !SHA256.test(request.skills.discoverySha256)) refuse("invalid Skills policy or discovery SHA-256");
  const snapshot = readManagedSkillPolicySnapshot(request.skills.dataDir);
  if (!snapshot || sha(snapshot.text) !== request.skills.policySha256) refuse("Skills policy preimage changed or is absent");
  const aliases = snapshot.value.bridge?.rootAliases ?? [];
  if (!Array.isArray(aliases)) refuse("Skills policy root aliases are invalid");
  try { recheckRootAliases(aliases as AgentRootAlias[]); } catch { refuse("Skills policy root alias changed or is invalid"); }
  const canonical = (path: string) => canonicalAgentPath(path, aliases as AgentRootAlias[]);
  const configRoot = canonical(join(request.native.home, ".claude"));
  canonicalDir(configRoot, "Claude config root");
  if (request.native.configRoot !== configRoot) refuse("Claude config root differs from the current resolver and reviewed root alias");
  const pluginRoot = join(configRoot, "plugins");
  if (process.env.CLAUDE_CODE_PLUGIN_CACHE_DIR) refuse("CLAUDE_CODE_PLUGIN_CACHE_DIR overrides are unsupported by this prospective schema; bind and review the actual cache root first");
  if (request.native.pluginRoot !== pluginRoot) refuse("Claude plugin root differs from the supported standard plugins directory; Cowork and custom cache roots require a separately bound schema");
  const pluginRootStat = lstatSync(pluginRoot, { throwIfNoEntry: false });
  if (pluginRootStat && (!pluginRootStat.isDirectory() || pluginRootStat.isSymbolicLink())) refuse("Claude plugin root is not a regular directory");
  keys(request.candidate, ["marketplace", "plugin", "root", "catalogPath", "catalogSha256", "closureSha256", "manifestPath", "manifestSha256"], "candidate");
  const candidate = request.candidate;
  canonicalDir(candidate.root, "candidate root");
  for (const [name, value] of [["marketplace", candidate.marketplace], ["plugin", candidate.plugin]] as const) {
    if (typeof value !== "string" || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(value)) refuse(`invalid candidate ${name}`);
  }
  for (const [name, path] of [["catalog", candidate.catalogPath], ["manifest", candidate.manifestPath]] as const) {
    abs(path, `${name} path`);
    if (path !== candidate.root && !path.startsWith(candidate.root + sep)) refuse(`${name} must be inside the frozen candidate root`);
  }
  if (!SHA256.test(candidate.catalogSha256) || !SHA256.test(candidate.closureSha256) || !SHA256.test(candidate.manifestSha256)) refuse("candidate digests must be lowercase SHA-256");
  if (captureClaudeProspectiveCandidateClosure(candidate.root) !== candidate.closureSha256) refuse("complete candidate closure changed");
  if (sha(safeFile(candidate.catalogPath, "candidate catalog")) !== candidate.catalogSha256) refuse("candidate catalog changed");
  if (basename(candidate.catalogPath) !== "marketplace.json") refuse("candidate catalog must be marketplace.json");
  const entry = captureClaudeMarketplaceEntry(candidate.catalogPath, candidate.marketplace, candidate.plugin);
  if (entry.sha256.length !== 64) refuse("candidate marketplace entry is invalid");
  if (basename(candidate.manifestPath) !== "plugin.json" || hashClaudePluginManifest(safeFile(candidate.manifestPath, "candidate plugin manifest").toString("utf8")) !== candidate.manifestSha256) refuse("candidate plugin manifest changed or is invalid");
  const pluginManifest = JSON.parse(safeFile(candidate.manifestPath, "candidate plugin manifest").toString("utf8"));
  if (!object(pluginManifest) || pluginManifest.name !== candidate.plugin) refuse("candidate plugin manifest identity differs from the selected entry");
  assertNoUnprojectedSkillPayload(candidate.root, candidate.catalogPath, candidate.marketplace, candidate.plugin, pluginManifest);

  if (!request.preimages || !object(request.preimages)) refuse("current Claude preimages are required");
  keys(request.preimages, ["settings", "userSettings", "projectSettings", "projectSettingsLocal", "marketplaces", "installedPlugins"], "current Claude preimages");
  for (const name of ["settings", "projectSettings", "projectSettingsLocal", "marketplaces", "installedPlugins"] as const) keys(request.preimages[name], ["path", "sha256"], `${name} preimage`);
  const expectedPaths = {
    settings: request.scope.kind === "project" ? canonical(join(request.scope.projectPath, ".claude/settings.json")) : canonical(join(request.native.home, ".claude/settings.json")),
    userSettings: canonical(join(request.native.home, ".claude/settings.json")),
    projectSettings: canonical(join(request.scope.projectPath, ".claude/settings.json")),
    projectSettingsLocal: canonical(join(request.scope.projectPath, ".claude/settings.local.json")),
    marketplaces: canonical(join(request.native.home, ".claude/plugins/known_marketplaces.json")),
    installedPlugins: canonical(join(request.native.home, ".claude/plugins/installed_plugins.json")),
  };
  for (const name of Object.keys(expectedPaths) as Array<keyof typeof expectedPaths>) {
    const witness = request.preimages[name];
    if (witness.path !== expectedPaths[name]) refuse(`${name} preimage path is not the selected Claude path`);
    readWitness(witness.path, witness.sha256, name);
  }
  if (!request.review || request.review.pluginHooks !== "reviewed-no-skill-injection") refuse("an explicit no-skill-injection review is required");
  if (request.skills.discoveryInputs?.version !== 1 || !Array.isArray(request.skills.discoveryInputs.agents) || request.skills.discoveryInputs.agents.length !== 1 || request.skills.discoveryInputs.agents[0]?.agent !== "claude" || request.skills.discoveryInputs.agents[0]?.pluginHooks !== "reviewed-no-skill-injection") refuse("one explicit reviewed Claude discovery binding is required");
  const reviewedPaths = new Set(request.skills.discoveryInputs.agents[0]!.sources.map(source => source.path));
  for (const path of new Set(Object.values(expectedPaths))) if (!reviewedPaths.has(path)) refuse("Skills discovery review does not bind every current user/project Claude settings and registration source");
  const binding = resolveAgentDiscovery({ home: request.native.home, agent: "claude", canonical, reviewed: request.skills.discoveryInputs });
  verifyAgentDiscovery(binding);
  if (sha(JSON.stringify(binding)) !== request.skills.discoverySha256) refuse("Skills discovery preimage differs from its reviewed binding");
  assertProjectDiscovery("claude", [request.scope.projectPath], request.native.home, canonical, binding);
  const stored = snapshot.value.bridge?.discovery?.claude;
  if (!stored || !isDeepStrictEqual(stored, binding) || snapshot.value.bridge?.home !== request.native.home) refuse("Skills policy does not bind the reviewed current Claude discovery");

  const delta = request.delta;
  keys(delta, ["settingsAfter", "knownMarketplacesAfter", "installedPluginsAfter"], "complete semantic delta");
  for (const [key, value] of Object.entries(delta)) if (!object(value)) refuse(`${key} must be a complete JSON object`);
  const pluginId = `${candidate.plugin}@${candidate.marketplace}`;
  const settings = jsonFile(expectedPaths.settings, "Claude settings");
  if (settings && settings.enabledPlugins !== undefined && !object(settings.enabledPlugins)) refuse("current settings enabledPlugins is not an object");
  const marketplaces = jsonFile(expectedPaths.marketplaces, "Claude known marketplaces");
  const registrations = jsonFile(expectedPaths.installedPlugins, "Claude installed plugins");
  if (registrations && (registrations.version !== 2 || !object(registrations.plugins))) refuse("current installed plugin registry has an unsupported shape");
  const hasCurrentPluginKey = !!registrations && Object.prototype.hasOwnProperty.call(registrations.plugins, pluginId);
  const currentRows = hasCurrentPluginKey ? registrations!.plugins[pluginId] : [];
  if (!Array.isArray(currentRows)) refuse("current selected plugin registrations are malformed");
  for (const row of currentRows) {
    if (!object(row) || !["user", "project", "local"].includes(row.scope) || typeof row.installPath !== "string") refuse("current selected plugin registration row is malformed");
    abs(row.installPath, "registered plugin install path");
    if (row.version !== undefined && (typeof row.version !== "string" || !row.version)) refuse("current selected plugin registration version is malformed");
    if (row.scope === "project") { abs(row.projectPath, "registered plugin project path"); }
    else if (row.projectPath !== undefined) refuse("non-project plugin registration has a project path");
  }
  const isTargetScopeRow = (row: any) => row?.scope === request.scope.kind && (request.scope.kind === "user" ? row.projectPath === undefined : row.projectPath === request.scope.projectPath);
  const targetRows = currentRows.filter(isTargetScopeRow);
  if (targetRows.length > 1) refuse("current selected-scope plugin registrations are ambiguous");
  const existingTarget = targetRows[0];
  if (existingTarget !== undefined && (!object(existingTarget) || Object.keys(existingTarget).some(key => !["scope", "projectPath", "installPath", "version", "installedAt", "lastUpdated"].includes(key)))) refuse("current selected-scope plugin registration has unsupported fields");
  for (const key of ["installedAt", "lastUpdated"] as const) if (existingTarget?.[key] !== undefined && !validUtcTimestamp(existingTarget[key])) refuse(`current selected-scope plugin ${key} field is invalid`);
  const catalog = JSON.parse(safeFile(candidate.catalogPath, "candidate catalog").toString("utf8")) as Record<string, any>;
  const selectedEntry = catalog.plugins.find((entry: unknown) => object(entry) && entry.name === candidate.plugin);
  const manifestVersion = (JSON.parse(safeFile(candidate.manifestPath, "candidate plugin manifest").toString("utf8")) as Record<string, unknown>).version;
  if (typeof manifestVersion !== "string" || !manifestVersion) refuse("candidate manifest lacks a concrete version");
  if (typeof selectedEntry?.version !== "string" || selectedEntry.version !== manifestVersion) refuse("candidate manifest version differs from the selected marketplace entry version");
  const sanitizeComponent = (value: string) => value.replace(/[^A-Za-z0-9_-]/g, "-");
  const sanitizedVersion = manifestVersion === "." || manifestVersion === ".." ? "-" : manifestVersion.replace(/[^A-Za-z0-9._-]/g, "-");
  if (manifestVersion.length > 256 || /[\x00-\x1f\x7f/\\]/.test(manifestVersion) || !sanitizedVersion) refuse("candidate version is not a supported native cache component");
  const expectedInstallPath = join(pluginRoot, "cache", sanitizeComponent(candidate.marketplace), sanitizeComponent(candidate.plugin), sanitizedVersion);
  if (expectedInstallPath.length > 4096) refuse("candidate native cache path exceeds its bound");
  const targetRegistration = {
    scope: request.scope.kind,
    ...(request.scope.kind === "project" ? { projectPath: request.scope.projectPath } : {}),
    installPath: expectedInstallPath,
    version: manifestVersion,
    ...(existingTarget ? {
      ...(existingTarget.installedAt === undefined ? {} : { installedAt: existingTarget.installedAt }),
      lastUpdated: existingTarget.lastUpdated === undefined ? GENERATED_PLUGIN_UPDATE_TIME : preserveOrGenerateTimestamp(existingTarget.lastUpdated, "installed_plugins.selected-row.lastUpdated"),
    } : { installedAt: GENERATED_FRESH_PLUGIN_INSTALLED_AT, lastUpdated: GENERATED_PLUGIN_UPDATE_TIME }),
  };
  const sourcePath = object(selectedEntry) ? selectedEntry.source : undefined;
  const candidatePluginRoot = dirname(dirname(candidate.manifestPath));
  const marketplaceRoot = dirname(dirname(candidate.catalogPath));
  const sourceRelativePath = relative(candidate.root, candidatePluginRoot).split(sep).join("/");
  const expectedSourcePath = sourceRelativePath === "." ? "./" : `./${sourceRelativePath}`;
  if (typeof sourcePath !== "string" || isAbsolute(sourcePath) || sourcePath !== expectedSourcePath
    || resolve(marketplaceRoot, sourcePath) !== candidatePluginRoot) refuse("marketplace source does not resolve to the frozen plugin closure; external source mapping is not supported by this schema");

  const settingsAfter = settings ? structuredClone(settings) : {};
  if (settingsAfter.enabledPlugins === undefined) settingsAfter.enabledPlugins = {};
  if (!object(settingsAfter.enabledPlugins)) refuse("target settings enabledPlugins is not an object");
  settingsAfter.enabledPlugins[pluginId] = true;
  if (!isDeepStrictEqual(delta.settingsAfter, settingsAfter)) refuse("complete settings document differs from the exact selected-plugin enablement operation");

  const marketplaceRowBefore = marketplaces?.[candidate.marketplace];
  if (marketplaceRowBefore !== undefined && !object(marketplaceRowBefore)) refuse("current marketplace row has an unsupported shape");
  if (marketplaceRowBefore !== undefined && Object.keys(marketplaceRowBefore).some(key => !["source", "installLocation", "autoUpdate", "lastUpdated"].includes(key))) refuse("current marketplace row has unsupported fields");
  if (marketplaceRowBefore?.autoUpdate !== undefined && typeof marketplaceRowBefore.autoUpdate !== "boolean") refuse("current marketplace autoUpdate field is invalid");
  if (marketplaceRowBefore?.lastUpdated !== undefined && !validUtcTimestamp(marketplaceRowBefore.lastUpdated)) refuse("current marketplace update timestamp is invalid");
  // Claude's registered local-directory marketplace materializes at its
  // source directory. The plugin cache is separate and is bound above.
  const targetMarketplaceLocation = candidate.root;
  const sameMarketplaceSource = isDeepStrictEqual(marketplaceRowBefore?.source, { source: "directory", path: candidate.root })
    && marketplaceRowBefore?.installLocation === targetMarketplaceLocation;
  const afterMarketplace: Record<string, unknown> = {
    source: { source: "directory", path: candidate.root },
    installLocation: targetMarketplaceLocation,
    autoUpdate: false,
    lastUpdated: sameMarketplaceSource && marketplaceRowBefore?.lastUpdated !== undefined
      ? preserveOrGenerateTimestamp(marketplaceRowBefore.lastUpdated, "known-marketplaces.lastUpdated")
      : GENERATED_MARKETPLACE_TIME,
  };
  if (afterMarketplace.installLocation !== candidate.root || afterMarketplace.autoUpdate !== false) refuse("owned marketplace row is invalid");
  const marketplacesAfter = marketplaces ? structuredClone(marketplaces) : {};
  marketplacesAfter[candidate.marketplace] = afterMarketplace;
  if (!isDeepStrictEqual(delta.knownMarketplacesAfter, marketplacesAfter)) refuse("complete marketplace document differs from the exact selected-directory marketplace operation");

  const installedAfter = registrations ? structuredClone(registrations) : { version: 2, plugins: {} };
  if (installedAfter.plugins === undefined) installedAfter.plugins = {};
  if (!object(installedAfter.plugins)) refuse("current installed plugin registry has an unsupported shape");
  const otherRows = currentRows.filter((row: any) => !isTargetScopeRow(row));
  installedAfter.plugins[pluginId] = [...otherRows, targetRegistration];
  if (!isDeepStrictEqual(delta.installedPluginsAfter, installedAfter)) refuse("complete installed plugin document changes an unrelated registration or has a target row not derived from the candidate");

  const expectedAfter = { targetSettingsPath: expectedPaths.settings, settings: settingsAfter, knownMarketplaces: marketplacesAfter, installedPlugins: installedAfter };
  const semanticDocumentsSha256 = sha(canonicalJson({ settings: settingsAfter, knownMarketplaces: marketplacesAfter, installedPlugins: installedAfter }));
  const exactPreimages = Object.keys(expectedPaths).map(name => ({ name, path: expectedPaths[name as keyof typeof expectedPaths], sha256: request.preimages[name as keyof typeof expectedPaths].sha256 }));
  const expectedPostStateSha256 = sha(canonicalJson({ paths: expectedPaths, targetSettingsPath: expectedPaths.settings, semanticDocumentsSha256, currentPreimages: exactPreimages }));
  const operationSha256 = sha(canonicalJson({ scope: request.scope, native: request.native, candidate: request.candidate, paths: expectedPaths,
    preimages: exactPreimages, skills: { dataDir: request.skills.dataDir, policySha256: request.skills.policySha256, discoverySha256: request.skills.discoverySha256 }, review: request.review, semanticDocumentsSha256 }));
  return {
    schema: CLAUDE_PROSPECTIVE_REVIEW_SCHEMA, accepted: true, applied: false, scope: request.scope, pluginId,
    native: { executablePath: request.native.executable.path, executableTarget: request.native.executable.target, executableVersion: request.native.executable.version, executableSha256: request.native.executable.sha256, configRoot: request.native.configRoot, pluginRoot: request.native.pluginRoot },
    candidate: { marketplace: candidate.marketplace, plugin: candidate.plugin, closureSha256: candidate.closureSha256, catalogSha256: candidate.catalogSha256, manifestSha256: candidate.manifestSha256 },
    targetSettingsPath: expectedPaths.settings,
    skillsDiscoverySha256: request.skills.discoverySha256,
    requestFileSha256,
    semanticDocumentsSha256,
    operationSha256,
    expectedPostStateSha256,
    preimages: [
      { name: "settings", path: expectedPaths.settings, sha256: request.preimages.settings.sha256 },
      { name: "user-settings", path: expectedPaths.userSettings, sha256: request.preimages.userSettings.sha256 },
      { name: "project-settings", path: expectedPaths.projectSettings, sha256: request.preimages.projectSettings.sha256 },
      { name: "project-settings-local", path: expectedPaths.projectSettingsLocal, sha256: request.preimages.projectSettingsLocal.sha256 },
      { name: "known-marketplaces", path: expectedPaths.marketplaces, sha256: request.preimages.marketplaces.sha256 },
      { name: "installed-plugins", path: expectedPaths.installedPlugins, sha256: request.preimages.installedPlugins.sha256 },
      { name: "skills-policy", path: join(request.skills.dataDir, "agent-policy.json"), sha256: request.skills.policySha256 },
    ],
    ownedDelta: { settingsEnabledPlugin: pluginId, knownMarketplace: candidate.marketplace, installedPlugin: pluginId, unrelatedGraph: "preserved-by-complete-semantic-documents" },
    identityPrecondition: "Harnesses must resolve the installed Claude home/config/plugin roots and executable path/version/hash plus the installed Skills data directory through their package-owned consumers, then compare every value before trusting this receipt; this validator checks supplied paths and current bytes only and does not establish actual consumer identity",
    reviewPrecondition: "The caller's no-skill-injection assessment is bound to the raw request hash; structural checks are not semantic hook review, and Harnesses must retain its existing review record and verify the exact candidate binding",
    limitation: "validation-only; native installer atomicity and crash recovery are not established",
  };
}
