import type { Preset, SchemaField } from "./types";

export const PRESET_SCHEMAS: Record<Preset, SchemaField> = {
  users: {
    id: "uuid",
    firstName: "firstName",
    lastName: "lastName",
    email: "email",
    phone: "phone",
    dateOfBirth: "date",
    username: "username",
    avatarUrl: "avatarUrl",
    address: "address",
    city: "city",
    state: "state",
    zipCode: "zipCode",
    country: "country",
  },
  products: {
    id: "uuid",
    name: "productName",
    description: "paragraph",
    price: "price",
    category: "category",
    sku: "sku",
    stock: "number",
    brand: "company",
    imageUrl: "imageUrl",
    rating: "rating",
  },
  orders: {
    orderId: "uuid",
    customerId: "uuid",
    customerName: "name",
    customerEmail: "email",
    orderDate: "date",
    items: "orderItems",
    subtotal: "price",
    tax: "price",
    shipping: "price",
    total: "price",
    status: "orderStatus",
    trackingNumber: "trackingNumber",
  },
  companies: {
    id: "uuid",
    name: "company",
    industry: "industry",
    employees: "number",
    foundedYear: "year",
    revenue: "price",
    website: "url",
    description: "paragraph",
    logoUrl: "imageUrl",
    address: "address",
    city: "city",
    country: "country",
  },
  articles: {
    id: "uuid",
    title: "title",
    author: "name",
    content: "paragraph",
    excerpt: "sentence",
    publishedDate: "date",
    tags: "tags",
    category: "category",
    readingTime: "number",
    viewCount: "number",
    imageUrl: "imageUrl",
  },
  reviews: {
    id: "uuid",
    reviewerName: "name",
    rating: "rating",
    title: "sentence",
    text: "paragraph",
    date: "date",
    verifiedPurchase: "boolean",
    helpfulCount: "number",
    productId: "uuid",
  },
  events: {
    id: "uuid",
    name: "title",
    description: "paragraph",
    startDate: "date",
    endDate: "date",
    location: "address",
    organizer: "name",
    category: "category",
    attendees: "number",
    ticketPrice: "price",
    status: "eventStatus",
  },
  transactions: {
    transactionId: "uuid",
    amount: "price",
    currency: "currency",
    type: "transactionType",
    date: "date",
    description: "sentence",
    fromAccount: "accountNumber",
    toAccount: "accountNumber",
    status: "transactionStatus",
    balance: "price",
  },
};

// Seeded random number generator
