import type { Content, Tokens } from "./types.js";

export function siteReadme(content: Content, tokens: Tokens, sections: string[]): string {
  return `# ${content.name} — one page site

Generated by the \`one-page-website\` skill. Everything in this folder is static:
no build step, no bundler, no external requests.

## Run it locally

\`\`\`bash
# any static server works
python3 -m http.server 8000
bunx serve .
npx http-server .
\`\`\`

Then open <http://localhost:8000>.

## Files

| File | Purpose |
|------|---------|
| \`index.html\` | The whole page. The stylesheet is inlined in \`<style>\` so the page renders with a single request. |
| \`styles.css\` | The identical stylesheet as a standalone file, if you would rather link it. See "Splitting the CSS" below. |
| \`script.js\` | Progressive enhancement: mobile nav, single-open FAQ, smooth scroll with focus management, scrollspy, header shadow. |

## Splitting the CSS

\`index.html\` inlines the stylesheet to keep the page to one request. If you
prefer a cached external stylesheet, delete the \`<style>\` block and add:

\`\`\`html
<link rel="stylesheet" href="styles.css">
\`\`\`

\`styles.css\` is byte-identical to the inlined block, so nothing else changes.

## Design tokens

All design decisions are CSS custom properties on \`:root\` in the stylesheet:

- \`--accent\` is \`${tokens.accent}\` (style preset: \`${tokens.preset}\`)
- \`--font-display\`, \`--font-sans\`, \`--font-mono\` — system stacks, no webfont requests
- \`--radius\`, \`--radius-lg\`, \`--measure\`, \`--container\`, \`--space-*\`

Dark mode is a \`@media (prefers-color-scheme: dark)\` block that overrides only
the color tokens. Change a token once and both themes follow.

## Accessibility notes

- Skip link to \`#main\`, landmark elements, one \`<h1>\`.
- The FAQ uses native \`<details>\`/\`<summary>\`, so it opens and closes with
  JavaScript disabled. The script only adds single-open behaviour.
- The mobile menu button is \`hidden\` in the markup and revealed by the script.
  Without JavaScript the nav list is always visible instead of being trapped
  behind a dead button.
- Anchor navigation moves focus to the target so keyboard and screen reader
  users land where sighted users do.
- \`prefers-reduced-motion\` disables smooth scrolling.

## Sections in this build

${sections.map((section) => `- \`#${section}\``).join("\n")}

## Replacing the copy

Edit \`index.html\` directly, or re-run the skill with \`--copy your-copy.md\` to
inject real markdown per section.
`;
}

export function deployNotes(content: Content): string {
  return `# Deploy notes — ${content.name}

The \`site/\` folder is a complete static site. There is no build step and no
runtime dependency; anything that serves files will serve it.

## Checklist before you ship

- [ ] Replace the placeholder copy (search \`index.html\` for \`example.com\`).
- [ ] Point \`mailto:hello@example.com\` at a real inbox or swap it for your form URL.
- [ ] Add a real favicon and an \`og:image\` (1200x630) and reference them in \`<head>\`.
- [ ] Set \`<link rel="canonical">\` to the production URL.
- [ ] Add \`/privacy\` and \`/terms\` pages, or remove the footer links.
- [ ] Run Lighthouse. The page ships accessible, but your copy and images decide the final score.

## Static hosts

\`\`\`bash
# Netlify
netlify deploy --dir=site --prod

# Cloudflare Pages
wrangler pages deploy site

# GitHub Pages (from a docs/ folder or gh-pages branch)
cp -r site/* docs/ && git add docs && git commit -m "Publish site"

# S3 + CloudFront
aws s3 sync site/ s3://YOUR_BUCKET/ --delete
aws cloudfront create-invalidation --distribution-id YOUR_ID --paths '/*'
\`\`\`

## Caching

\`index.html\` inlines its CSS, so a cold visit is one HTML request plus
\`script.js\`. Suggested headers:

\`\`\`
/index.html    Cache-Control: public, max-age=0, must-revalidate
/script.js     Cache-Control: public, max-age=31536000, immutable
/styles.css    Cache-Control: public, max-age=31536000, immutable
\`\`\`

Add a content hash to \`script.js\` if you adopt the immutable header.

## Security headers

\`\`\`
Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; img-src 'self' data:
Referrer-Policy: strict-origin-when-cross-origin
X-Content-Type-Options: nosniff
\`\`\`

\`'unsafe-inline'\` is needed for the inlined \`<style>\` block and the two-line
no-js class swap in \`<head>\`. Move the CSS to \`styles.css\` and delete that
inline script if you want a stricter policy.
`;
}

export function copyDoc(content: Content, sections: string[]): string {
  return `# Copy — ${content.name}

This is the copy that was written into \`site/index.html\`. Edit it, then re-run
the skill with \`--copy copy.md\` to feed it back in.

# ${content.tagline}

${content.lead}

${sections.includes("features") ? `## Features\n\n${content.features.map((f) => `### ${f.title}\n\n${f.body}`).join("\n\n")}\n` : ""}
${sections.includes("proof") ? `## Proof\n\n${content.stats.map((s) => `- **${s.value}** — ${s.label}`).join("\n")}\n\n> ${content.quote.text}\n>\n> — ${content.quote.author}, ${content.quote.role}\n` : ""}
${
  sections.includes("pricing")
    ? `## Pricing\n\n${content.tiers
        .map((t) => `### ${t.name} — ${t.price} ${t.cadence}\n\n${t.blurb}\n\n${t.items.map((i) => `- ${i}`).join("\n")}`)
        .join("\n\n")}\n`
    : ""
}
${sections.includes("faq") ? `## FAQ\n\n${content.faqs.map((f) => `**${f.q}**\n\n${f.a}`).join("\n\n")}\n` : ""}
${sections.includes("cta") ? `## CTA\n\n### ${content.ctaHeading}\n\n${content.ctaBody}\n` : ""}`;
}

/* ------------------------------------------------------------------ */
/* cli                                                                 */
/* ------------------------------------------------------------------ */


