/**
 * init / export / import — project setup and sharing commands
 */

import chalk from "chalk";
import { existsSync, readFileSync, writeFileSync, appendFileSync } from "fs";
import { join } from "path";
import type { Command } from "commander";
import { getSkillRequirements, detectProjectSkills } from "../../lib/skillinfo.js";
import { getInstalledSkills, resolveAgents, type AgentTarget } from "../../lib/installer.js";

export function registerSetup(parent: Command) {
  // Init
  parent
    .command("init")
    .option("--json", "Output as JSON", false)
    .option("--for <agent>", "Detect project type and show MCP registration guidance for agent")
    .option("--scope <scope>", "Deprecated; agent skill-folder installs are disabled", "global")
    .description("Initialize project for pinned skills (.env.example, .gitignore)")
    .action((options: { json: boolean; for?: string; scope: string }) => handleInit(options));

  // Export
  parent
    .command("export")
    .option("--json", "Output as JSON (default behavior)", false)
    .description("Export pinned skills to JSON for sharing or backup")
    .action((_options: { json: boolean }) => handleExport());

  // Import
  parent
    .command("import")
    .argument("<file>", "JSON file to import (use - for stdin)")
    .option("--json", "Output results as JSON", false)
    .option("--for <agent>", "Deprecated: use skills mcp --register <agent|all>")
    .option("--scope <scope>", "Deprecated agent install scope", "global")
    .option("--dry-run", "Show what would be pinned without actually writing project pins", false)
    .description("Import and pin skills from a JSON export file")
    .action(async (file: string, options) => handleImport(file, options));
}

async function handleInit(options: { json: boolean; for?: string; scope: string }) {
  const cwd = process.cwd();

  if (options.for) {
    let agents: AgentTarget[];
    try { agents = resolveAgents(options.for); }
    catch (err) {
      if (options.json) console.log(JSON.stringify({ error: (err as Error).message }));
      else console.error(chalk.red((err as Error).message));
      process.exitCode = 1; return;
    }

    const { detected, recommended } = detectProjectSkills(cwd);

    if (options.json) {
      console.log(JSON.stringify({
        detected,
        recommended: recommended.map((s) => s.name),
        agents,
        mcpRegister: `skills mcp --register ${options.for}`,
      }, null, 2));
      return;
    }

    if (detected.length > 0) {
      console.log(chalk.bold("\nDetected project technologies:"));
      for (const tech of detected) console.log(`  ${chalk.cyan(tech)}`);
    } else console.log(chalk.dim("\nNo specific project dependencies detected"));

    console.log(chalk.bold(`\nRecommended skills (${recommended.length}):`));
    for (const skill of recommended) console.log(`  ${chalk.cyan(skill.name)} - ${skill.description}`);

    console.log(chalk.bold(`\nRecommended skills are available through Skills MCP.\n`));
    for (const agent of agents) console.log(chalk.dim(`  ${agent}: skills mcp --register ${agent}`));
    console.log(chalk.dim(`\nUse: skills mcp --register ${options.for}`));
  }

  const installed = getInstalledSkills();
  if (!installed.length && !options.for) {
    console.log(options.json ? JSON.stringify({ skills: [], envVars: 0, gitignoreUpdated: false }) : chalk.dim("No pinned skills. Run: skills pin <name>"));
    return;
  }
  if (!installed.length) return;

  const envMap = new Map<string, string[]>();
  for (const name of installed) {
    const reqs = getSkillRequirements(name);
    if (reqs?.envVars.length) for (const v of reqs.envVars) {
      if (!envMap.has(v)) envMap.set(v, []);
      if (!envMap.get(v)!.includes(name)) envMap.get(v)!.push(name);
    }
  }

  let envVarCount = 0;
  if (envMap.size > 0) {
    const lines = ["# Environment variables for pinned skills", "# Auto-generated by: skills init", ""];
    const sorted = Array.from(envMap.entries()).sort(([a], [b]) => a.localeCompare(b));
    let lastPrefix = "";
    for (const [envVar, skills] of sorted) {
      const prefix = envVar.split("_")[0];
      if (prefix !== lastPrefix) { if (lastPrefix) lines.push(""); lines.push(`# ${prefix}`); lastPrefix = prefix; }
      lines.push(`# Used by: ${skills.join(", ")}`);
      lines.push(`${envVar}=`);
    }
    writeFileSync(join(cwd, ".env.example"), lines.join("\n") + "\n");
    envVarCount = envMap.size;
    if (!options.json) console.log(chalk.green(`\u2713 Generated .env.example (${envVarCount} variables from ${installed.length} skills)`));
  } else if (!options.json) console.log(chalk.dim("  No environment variables detected across pinned skills"));

  const gitignorePath = join(cwd, ".gitignore");
  const gitignoreEntries = [".skills/runs/", ".skills/exports/", ".skills/tmp/"];
  let gitignoreContent = existsSync(gitignorePath) ? readFileSync(gitignorePath, "utf-8") : "";
  let gitignoreUpdated = false;
  const missingEntries = gitignoreEntries.filter((entry) => !gitignoreContent.includes(entry));
  if (missingEntries.length > 0) {
    const addition = `${gitignoreContent.endsWith("\n") || gitignoreContent === "" ? "\n" : "\n\n"}# Skills runtime outputs\n${missingEntries.join("\n")}\n`;
    appendFileSync(gitignorePath, addition);
    gitignoreUpdated = true;
    if (!options.json) console.log(chalk.green(`\u2713 Added Skills runtime outputs to .gitignore`));
  } else if (!options.json) console.log(chalk.dim("  Skills runtime outputs already in .gitignore"));

  if (!options.for) {
    if (options.json) console.log(JSON.stringify({ skills: installed, envVars: envVarCount, gitignoreUpdated }, null, 2));
    else {
      if (envMap.size > 0) {
        console.log(chalk.bold("\nSkill environment requirements:"));
        for (const name of installed) {
          const reqs = getSkillRequirements(name);
          if (reqs?.envVars.length) console.log(`  ${chalk.cyan(name)}: ${reqs.envVars.join(", ")}`);
        }
      }
      console.log(chalk.bold(`\nInitialized for ${installed.length} pinned skill(s)`));
    }
  }
}

function handleExport() {
  const skills = getInstalledSkills();
  console.log(JSON.stringify({ version: 1, skills, timestamp: new Date().toISOString() }, null, 2));
}

async function handleImport(file: string, options: { json: boolean; for?: string; scope: string; dryRun: boolean }) {
  let raw: string;
  try {
    if (file === "-") raw = await new Response(process.stdin as unknown as ReadableStream).text();
    else {
      if (!existsSync(file)) {
        const error = `File not found: ${file}`;
        if (options.json) console.log(JSON.stringify({ imported: 0, error }));
        else console.error(chalk.red(error));
        process.exitCode = 1; return;
      }
      raw = readFileSync(file, "utf-8");
    }
  } catch (err) {
    const error = `Failed to read file: ${(err as Error).message}`;
    if (options.json) console.log(JSON.stringify({ imported: 0, error }));
    else console.error(chalk.red(error));
    process.exitCode = 1; return;
  }

  let payload: { version: number; skills: string[]; timestamp?: string };
  try { payload = JSON.parse(raw); } catch {
    const error = "Invalid JSON in import file";
    if (options.json) console.log(JSON.stringify({ imported: 0, error }));
    else console.error(chalk.red(error));
    process.exitCode = 1; return;
  }
  if (!payload || typeof payload !== "object" || !Array.isArray(payload.skills)) {
    const error = 'Invalid format: expected { "version": 1, "skills": [...] }';
    if (options.json) console.log(JSON.stringify({ imported: 0, error }));
    else console.error(chalk.red(error));
    process.exitCode = 1; return;
  }

  const skillList = payload.skills;
  if (!skillList.length) { console.log(options.json ? JSON.stringify({ imported: 0, results: [] }) : chalk.dim("No skills to import")); return; }

  if (options.dryRun) {
    if (options.json) console.log(JSON.stringify({ dryRun: true, skills: skillList }));
    else {
      console.log(chalk.bold(`\n[dry-run] Would pin ${skillList.length} skill(s):\n`));
      for (let i = 0; i < skillList.length; i++) console.log(chalk.dim(`  [${i + 1}/${skillList.length}] ${skillList[i]}${options.for ? ` via MCP for ${options.for}` : " in .skills/project.json"}`));
    }
    return;
  }

  const results = [];
  if (options.for) {
    let agents: AgentTarget[];
    try { agents = resolveAgents(options.for); }
    catch (err) {
      if (options.json) console.log(JSON.stringify({ imported: 0, total: skillList.length, error: (err as Error).message }));
      else console.error(chalk.red((err as Error).message));
      process.exitCode = 1; return;
    }
    for (let i = 0; i < skillList.length; i++) {
      const name = skillList[i];
      results.push({ skill: name, success: true, agents, mcpRegister: `skills mcp --register ${options.for}` });
      if (!options.json) process.stdout.write(`[${i + 1}/${skillList.length}] ${name}: available through Skills MCP\n`);
    }
  } else {
    const { installSkill } = await import("../../lib/installer.js");
    for (let i = 0; i < skillList.length; i++) {
      const name = skillList[i];
      const result = installSkill(name);
      results.push(result);
      if (!options.json) process.stdout.write(`[${i + 1}/${skillList.length}] Pinning ${name}...${result.success ? " done" : " failed"}\n`);
    }
  }

  if (options.json) console.log(JSON.stringify({ imported: results.filter((r) => r.success).length, total: skillList.length, results }));
  else {
    const succeeded = results.filter((r) => r.success).length;
    console.log(chalk.bold(`\nImported ${succeeded}/${skillList.length} pin(s)${skillList.length - succeeded > 0 ? ` (${skillList.length - succeeded} failed)` : ""}`));
  }
  if (results.some((r) => !r.success)) process.exitCode = 1;
}
